# Generated by Django 2.2.1 on 2019-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Valor')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=7, max_digits=15, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo umbral %')),
                ('usado_para_mensual', models.BooleanField(default=False, verbose_name='Usado para mes')),
            ],
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_velo_usado_p_543256_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_velo_fecha_9cd670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='velocidadviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_temp_usado_p_40c0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_temp_fecha_8b2bf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_temp_usado_p_1e1d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_temp_fecha_d321c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_radi_usado_p_09911a_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_radi_fecha_faa8b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiacionsolar',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_pres_usado_p_7658d3_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_pres_fecha_b909a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presionatmosferica',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_prec_usado_p_6b3d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_prec_fecha_dbeb47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_nive_usado_p_da5dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_nive_fecha_a70c9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivelagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_hume_usado_p_8feb25_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_hume_fecha_ddc017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadsuelo',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_hume_usado_p_6f69ae_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_hume_fecha_87b19f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_dire_usado_p_75cace_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_dire_fecha_fdfb4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direccionviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['usado_para_mensual', 'id'], name='diario_caud_usado_p_88d127_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='diario_caud_fecha_c4a6ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
