# Generated by Django 2.1.1 on 2019-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variable', '0001_initial'),
        ('estacion', '0001_initial'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='CurvaDescarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('funcion', models.CharField(max_length=80, verbose_name='Funcion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('med_fecha', models.DateTimeField(db_index=True, verbose_name='Fecha')),
                ('med_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('med_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('med_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('med_estado', models.NullBooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'ordering': ('med_fecha',),
            },
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteValidacion',
            fields=[
                ('numero_fila', models.BigAutoField(primary_key=True, serialize=False)),
                ('seleccionado', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('valor_seleccionado', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('variacion_consecutiva', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('comentario', models.CharField(max_length=350)),
                ('class_fila', models.CharField(max_length=30)),
                ('class_fecha', models.CharField(max_length=30)),
                ('class_validacion', models.CharField(max_length=30)),
                ('class_valor', models.CharField(max_length=30)),
                ('class_variacion_consecutiva', models.CharField(max_length=30)),
                ('class_stddev_error', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Viento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('vel_valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('vel_maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('vel_minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('dir_valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('dir_maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('dir_minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='VoltajeBateria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.AddIndex(
            model_name='voltajebateria',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_vo_estacio_2f4b75_idx'),
        ),
        migrations.AddIndex(
            model_name='voltajebateria',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_vo_fecha_a1e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_vi_estacio_bf1db5_idx'),
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_vi_fecha_6d74ae_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_ve_estacio_b73ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_ve_fecha_023d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_te_estacio_5955a1_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_te_fecha_396e65_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_te_estacio_38ed0b_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_te_fecha_be0aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_ra_estacio_a39f13_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_ra_fecha_ca81e4_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_pr_estacio_a202fe_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_pr_fecha_bb7ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_pr_estacio_aec455_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_pr_fecha_d55d18_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_ni_estacio_159657_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_ni_fecha_1ae364_idx'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='mar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='var_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_hu_estacio_fe4ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_hu_fecha_a4b426_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_hu_estacio_ef9102_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_hu_fecha_032b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_di_estacio_4544b6_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_di_fecha_615e05_idx'),
        ),
        migrations.AddField(
            model_name='curvadescarga',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_ca_estacio_555616_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_ca_fecha_da2171_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['est_id', 'med_fecha'], name='medicion_me_est_id__8b1caf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['med_fecha', 'est_id'], name='medicion_me_med_fec_0ceac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curvadescarga',
            unique_together={('estacion', 'fecha')},
        ),
    ]
