# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('marca', '0001_initial'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('med_fecha', models.DateTimeField(verbose_name='Fecha')),
                ('med_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('med_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('med_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('med_estado', models.NullBooleanField(default=True, verbose_name='Estado')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('mar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
            options={
                'ordering': ('med_fecha',),
            },
        ),
    ]
