# Generated by Django 2.0.3 on 2018-09-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0004_auto_20180814_1053'),
        ('medicion', '0002_auto_20180801_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaDescarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('funcion', models.CharField(max_length=80, verbose_name='Funcion')),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='curvadescarga',
            unique_together={('estacion', 'fecha')},
        ),
    ]
