# Generated by Django 2.1.1 on 2019-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0003_auto_20180924_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var10Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var11Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var1Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Var2Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var3Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var4Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var5Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var6Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var7Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var8Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Var9Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.AddIndex(
            model_name='var9medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_8c8c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='var9medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_96c6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='var8medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_cd5f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='var8medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_770bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='var7medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_7d05a1_idx'),
        ),
        migrations.AddIndex(
            model_name='var7medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_2a982c_idx'),
        ),
        migrations.AddIndex(
            model_name='var6medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_54120d_idx'),
        ),
        migrations.AddIndex(
            model_name='var6medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_df9b59_idx'),
        ),
        migrations.AddIndex(
            model_name='var5medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_8f5d36_idx'),
        ),
        migrations.AddIndex(
            model_name='var5medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_34a0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='var4medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_90d1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='var4medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_a2b8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='var3medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_e07323_idx'),
        ),
        migrations.AddIndex(
            model_name='var3medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_7d85ce_idx'),
        ),
        migrations.AddIndex(
            model_name='var2medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_f20903_idx'),
        ),
        migrations.AddIndex(
            model_name='var2medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_ab52e9_idx'),
        ),
        migrations.AddIndex(
            model_name='var1medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_a5d0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='var1medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_4d9477_idx'),
        ),
        migrations.AddIndex(
            model_name='var11medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_68c46b_idx'),
        ),
        migrations.AddIndex(
            model_name='var11medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_abe9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='var10medicion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_f707c7_idx'),
        ),
        migrations.AddIndex(
            model_name='var10medicion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_841425_idx'),
        ),
    ]
