# Generated by Django 2.1.1 on 2019-02-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0004_auto_20190211_1104'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['est_id', 'med_fecha'], name='medicion_me_est_id__8b1caf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['med_fecha', 'est_id'], name='medicion_me_med_fec_0ceac4_idx'),
        ),
    ]
