# Generated by Django 2.1.1 on 2019-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0005_auto_20190211_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion', models.PositiveIntegerField(verbose_name='Estacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Mínimo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Var1Medicion',
            new_name='Var1',
        ),
        migrations.RenameModel(
            old_name='Var10Medicion',
            new_name='Var10',
        ),
        migrations.RenameModel(
            old_name='Var5Medicion',
            new_name='Var11',
        ),
        migrations.RenameModel(
            old_name='Var2Medicion',
            new_name='Var2',
        ),
        migrations.RenameModel(
            old_name='Var11Medicion',
            new_name='Var3',
        ),
        migrations.RenameModel(
            old_name='Var6Medicion',
            new_name='Var4',
        ),
        migrations.RenameModel(
            old_name='Var8Medicion',
            new_name='Var5',
        ),
        migrations.RenameModel(
            old_name='Var9Medicion',
            new_name='Var6',
        ),
        migrations.RenameModel(
            old_name='Var4Medicion',
            new_name='Var7',
        ),
        migrations.RenameModel(
            old_name='Var7Medicion',
            new_name='Var8',
        ),
        migrations.RenameModel(
            old_name='Var3Medicion',
            new_name='Var9',
        ),
        migrations.RemoveIndex(
            model_name='var1',
            name='medicion_va_estacio_a5d0ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='var1',
            name='medicion_va_fecha_4d9477_idx',
        ),
        migrations.RemoveIndex(
            model_name='var10',
            name='medicion_va_estacio_f707c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='var10',
            name='medicion_va_fecha_841425_idx',
        ),
        migrations.RemoveIndex(
            model_name='var11',
            name='medicion_va_estacio_8f5d36_idx',
        ),
        migrations.RemoveIndex(
            model_name='var11',
            name='medicion_va_fecha_34a0f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='var2',
            name='medicion_va_estacio_f20903_idx',
        ),
        migrations.RemoveIndex(
            model_name='var2',
            name='medicion_va_fecha_ab52e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='var3',
            name='medicion_va_estacio_68c46b_idx',
        ),
        migrations.RemoveIndex(
            model_name='var3',
            name='medicion_va_fecha_abe9c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='var4',
            name='medicion_va_estacio_54120d_idx',
        ),
        migrations.RemoveIndex(
            model_name='var4',
            name='medicion_va_fecha_df9b59_idx',
        ),
        migrations.RemoveIndex(
            model_name='var5',
            name='medicion_va_estacio_cd5f0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='var5',
            name='medicion_va_fecha_770bd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='var6',
            name='medicion_va_estacio_8c8c0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='var6',
            name='medicion_va_fecha_96c6ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='var7',
            name='medicion_va_estacio_90d1e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='var7',
            name='medicion_va_fecha_a2b8a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='var8',
            name='medicion_va_estacio_7d05a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='var8',
            name='medicion_va_fecha_2a982c_idx',
        ),
        migrations.RemoveIndex(
            model_name='var9',
            name='medicion_va_estacio_e07323_idx',
        ),
        migrations.RemoveIndex(
            model_name='var9',
            name='medicion_va_fecha_7d85ce_idx',
        ),
        migrations.AddIndex(
            model_name='var1',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_48ce32_idx'),
        ),
        migrations.AddIndex(
            model_name='var1',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_230e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='var10',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_5a55b7_idx'),
        ),
        migrations.AddIndex(
            model_name='var10',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_cadc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='var11',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_1f64c9_idx'),
        ),
        migrations.AddIndex(
            model_name='var11',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_a1a143_idx'),
        ),
        migrations.AddIndex(
            model_name='var2',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_226c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='var2',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_fd08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='var3',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_888495_idx'),
        ),
        migrations.AddIndex(
            model_name='var3',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_cd4825_idx'),
        ),
        migrations.AddIndex(
            model_name='var4',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_db69f2_idx'),
        ),
        migrations.AddIndex(
            model_name='var4',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_226009_idx'),
        ),
        migrations.AddIndex(
            model_name='var5',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_8b8ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='var5',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_b58509_idx'),
        ),
        migrations.AddIndex(
            model_name='var6',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_803e71_idx'),
        ),
        migrations.AddIndex(
            model_name='var6',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_9f3407_idx'),
        ),
        migrations.AddIndex(
            model_name='var7',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_9cf4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='var7',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_3ad978_idx'),
        ),
        migrations.AddIndex(
            model_name='var8',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_ab2045_idx'),
        ),
        migrations.AddIndex(
            model_name='var8',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_8f1713_idx'),
        ),
        migrations.AddIndex(
            model_name='var9',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_va_estacio_1c120f_idx'),
        ),
        migrations.AddIndex(
            model_name='var9',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_va_fecha_a15c83_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_te_estacio_5955a1_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_te_fecha_396e65_idx'),
        ),
    ]
