# Generated by Django 2.1.1 on 2019-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0007_auto_20190212_0941'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='precipitacion',
            name='medicion_pr_estacio_190a5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='precipitacion',
            name='medicion_pr_fecha_3b07e1_idx',
        ),
        migrations.RenameField(
            model_name='precipitacion',
            old_name='estacion_id',
            new_name='estacion',
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['estacion', 'fecha'], name='medicion_pr_estacio_aec455_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion'], name='medicion_pr_fecha_d55d18_idx'),
        ),
    ]
