# Generated by Django 2.2.1 on 2019-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0008_auto_20190213_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturaaire',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AlterField(
            model_name='temperaturaaire',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='temperaturaaire',
            name='valor',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor'),
        ),
    ]
