# Generated by Django 2.2.1 on 2020-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0010_auto_20190923_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='caudal',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='direccionviento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='humedadaire',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='humedadsuelo',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='nivelagua',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='presionatmosferica',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='radiacionsolar',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='temperaturaagua',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='temperaturaaire',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='velocidadviento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='viento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.AddField(
            model_name='voltajebateria',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estacion_id'),
        ),
        migrations.DeleteModel(
            name='Medicion',
        ),
    ]
