# Generated by Django 2.2.1 on 2020-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0011_auto_20200225_1439'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caudal',
            name='medicion_ca_estacio_555616_idx',
        ),
        migrations.RemoveIndex(
            model_name='caudal',
            name='medicion_ca_fecha_da2171_idx',
        ),
        migrations.RemoveIndex(
            model_name='direccionviento',
            name='medicion_di_estacio_4544b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='direccionviento',
            name='medicion_di_fecha_615e05_idx',
        ),
        migrations.RemoveIndex(
            model_name='humedadaire',
            name='medicion_hu_estacio_ef9102_idx',
        ),
        migrations.RemoveIndex(
            model_name='humedadaire',
            name='medicion_hu_fecha_032b2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='humedadsuelo',
            name='medicion_hu_estacio_fe4ec1_idx',
        ),
        migrations.RemoveIndex(
            model_name='humedadsuelo',
            name='medicion_hu_fecha_a4b426_idx',
        ),
        migrations.RemoveIndex(
            model_name='nivelagua',
            name='medicion_ni_estacio_159657_idx',
        ),
        migrations.RemoveIndex(
            model_name='nivelagua',
            name='medicion_ni_fecha_1ae364_idx',
        ),
        migrations.RemoveIndex(
            model_name='precipitacion',
            name='medicion_pr_estacio_aec455_idx',
        ),
        migrations.RemoveIndex(
            model_name='precipitacion',
            name='medicion_pr_fecha_d55d18_idx',
        ),
        migrations.RemoveIndex(
            model_name='presionatmosferica',
            name='medicion_pr_estacio_a202fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='presionatmosferica',
            name='medicion_pr_fecha_bb7ccf_idx',
        ),
        migrations.RemoveIndex(
            model_name='radiacionsolar',
            name='medicion_ra_estacio_a39f13_idx',
        ),
        migrations.RemoveIndex(
            model_name='radiacionsolar',
            name='medicion_ra_fecha_ca81e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='temperaturaagua',
            name='medicion_te_estacio_38ed0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='temperaturaagua',
            name='medicion_te_fecha_be0aa9_idx',
        ),
        migrations.RemoveIndex(
            model_name='temperaturaaire',
            name='medicion_te_estacio_5955a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='temperaturaaire',
            name='medicion_te_fecha_396e65_idx',
        ),
        migrations.RemoveIndex(
            model_name='viento',
            name='medicion_vi_estacio_bf1db5_idx',
        ),
        migrations.RemoveIndex(
            model_name='viento',
            name='medicion_vi_fecha_6d74ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='voltajebateria',
            name='medicion_vo_estacio_2f4b75_idx',
        ),
        migrations.RemoveIndex(
            model_name='voltajebateria',
            name='medicion_vo_fecha_a1e1e7_idx',
        ),
        migrations.AlterField(
            model_name='caudal',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='direccionviento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='humedadaire',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='humedadsuelo',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='nivelagua',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='precipitacion',
            name='estacion',
            field=models.PositiveIntegerField(verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='precipitacion',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='presionatmosferica',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='radiacionsolar',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='temperaturaagua',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='temperaturaaire',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='velocidadviento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='viento',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AlterField(
            model_name='voltajebateria',
            name='estacion_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estacion'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_ca_estacio_0013ce_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_ca_fecha_fc7cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_di_estacio_b4a488_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_di_fecha_51ad69_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_hu_estacio_3b0b16_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_hu_fecha_9390bd_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_hu_estacio_f778c8_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_hu_fecha_037527_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_ni_estacio_6cbe95_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_ni_fecha_38312a_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_pr_estacio_190a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_pr_fecha_3b07e1_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_pr_estacio_6c0fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_pr_fecha_f5314d_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_ra_estacio_917a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_ra_fecha_b6ac8b_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_te_estacio_113b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_te_fecha_53625d_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_te_estacio_098f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_te_fecha_2be000_idx'),
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_vi_estacio_26405b_idx'),
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_vi_fecha_af5a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='voltajebateria',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_vo_estacio_a547cf_idx'),
        ),
        migrations.AddIndex(
            model_name='voltajebateria',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_vo_fecha_8b885b_idx'),
        ),
    ]
