# Generated by Django 2.2.1 on 2020-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0012_auto_20200226_0915'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='velocidadviento',
            name='medicion_ve_estacio_b73ed3_idx',
        ),
        migrations.RemoveIndex(
            model_name='velocidadviento',
            name='medicion_ve_fecha_023d1e_idx',
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['estacion_id', 'fecha'], name='medicion_ve_estacio_3296f6_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='medicion_ve_fecha_59e7ac_idx'),
        ),
    ]
