# Generated by Django 2.2.1 on 2020-03-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0014_auto_20200310_1629'),
        ('medicion', '0014_auto_20200226_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='VientoPolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('velocidad', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Velocidad')),
                ('direccion', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Direccion')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaudalViaEstacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha fin')),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('calibracion_regleta_sensor', models.NullBooleanField(default=False, verbose_name='Calibracion')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
        ),
    ]
