# Generated by Django 5.0.3 on 2024-03-13 15:44

from django.db import migrations

from ..initial_data import create_user_group


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_user_group)]
