# Generated by Django 3.0.11 on 2022-07-20 13:21

from django.db import migrations

from ..initial_data import populate_groups


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
        ("sensor", "0001_initial"),
        ("formatting", "0001_initial"),
        ("variable", "0001_initial"),
        ("measurement", "0001_initial"),
        ("importing", "0002_auto_20220720_1247"),
        ("management", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_groups)]
