# Generated by Django 5.2.8 on 2026-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thingsboard_access_token',
            field=models.CharField(blank=True, help_text='Thingsboard access token (preferred for scheduled pulls).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thingsboard_password',
            field=models.CharField(blank=True, help_text='Thingsboard password for data pulls.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thingsboard_username',
            field=models.CharField(blank=True, help_text='Thingsboard username for data pulls.', max_length=150, null=True),
        ),
    ]
