# Generated by Django 5.2.8 on 2026-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_thingsboardcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingsboardcredentials',
            name='thingsboard_customer_id',
            field=models.CharField(blank=True, help_text='Thingsboard customer ID (used for data retrieval).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thingsboardcredentials',
            name='thingsboard_access_token',
            field=models.CharField(blank=True, help_text='Thingsboard access token (preferred for scheduled pulls).', max_length=1000, null=True),
        ),
    ]
