# Generated by Django 2.0.3 on 2018-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('var_id', models.IntegerField(verbose_name='Variable')),
                ('est_id', models.IntegerField(verbose_name='Estación')),
                ('mar_id', models.IntegerField(verbose_name='Marca Datalogger')),
                ('med_fecha', models.DateTimeField(verbose_name='Fecha')),
                ('med_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('med_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('med_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('med_estado', models.NullBooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
