repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args: [--profile, black]
        exclude: |
          (?x)(
              ^unused_apps/
          )
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^migrations/|data/|venv
