repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.29.4"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Prettier supports many other file formats (e.g., JavaScript, HTML; see
        # https://prettier.io for list). Add other types here.
        types_or: [yaml, json]
  - repo: https://github.com/djlint/djLint
    rev: v1.36.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.4"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-toml, types-pytz]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "MD013", "--disable", "MD033"]
