site_name: Paricia
repo_url: https://github.com/ImperialCollegeLondon/paricia

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"
  - markdown_include.include:
      base_path: .
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
            members: true
          paths: [measurement]
  - caption:
      figure:
        ignore_classes: ["no-caption"]

nav:
  - Introduction: index.md
  - Contributing: contributing.md
  - Permissions: permissions.md
  - Validation: validation.md
  - Applications:
      - Index: Applications/index.md
      - Formatting: Applications/formatting.md
      - Variables: Applications/variable.md
      - Sensors: Applications/sensor.md
      - Stations: Applications/station.md
      - Measurements: Applications/measurement.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/
