TRUNCATE anuarios_radiacionmaxima RESTART IDENTITY;
TRUNCATE anuarios_radiacionminima RESTART IDENTITY;
TRUNCATE anuarios_viento RESTART IDENTITY;

TRUNCATE medicion_var1medicion RESTART IDENTITY;
TRUNCATE validacion_var1validado RESTART IDENTITY;
TRUNCATE horario_var1horario RESTART IDENTITY;
TRUNCATE diario_var1diario RESTART IDENTITY;
TRUNCATE mensual_var1mensual RESTART IDENTITY;
TRUNCATE anuarios_var1anuarios RESTART IDENTITY;
TRUNCATE anual_var1anual RESTART IDENTITY;

TRUNCATE medicion_var2medicion RESTART IDENTITY;
TRUNCATE validacion_var2validado RESTART IDENTITY;
TRUNCATE horario_var2horario RESTART IDENTITY;
TRUNCATE diario_var2diario RESTART IDENTITY;
TRUNCATE mensual_var2mensual RESTART IDENTITY;
TRUNCATE anuarios_var2anuarios RESTART IDENTITY;

TRUNCATE medicion_var3medicion RESTART IDENTITY;
TRUNCATE validacion_var3validado RESTART IDENTITY;
TRUNCATE horario_var3horario RESTART IDENTITY;
TRUNCATE diario_var3diario RESTART IDENTITY;
TRUNCATE mensual_var3mensual RESTART IDENTITY;
TRUNCATE anuarios_var3anuarios RESTART IDENTITY;

TRUNCATE medicion_var4medicion RESTART IDENTITY;
TRUNCATE validacion_var4validado RESTART IDENTITY;
TRUNCATE horario_var4horario RESTART IDENTITY;
TRUNCATE diario_var4diario RESTART IDENTITY;
TRUNCATE mensual_var4mensual RESTART IDENTITY;

TRUNCATE medicion_var5medicion RESTART IDENTITY;
TRUNCATE validacion_var5validado RESTART IDENTITY;
TRUNCATE horario_var5horario RESTART IDENTITY;
TRUNCATE diario_var5diario RESTART IDENTITY;
TRUNCATE mensual_var5mensual RESTART IDENTITY;

TRUNCATE medicion_var6medicion RESTART IDENTITY;
TRUNCATE validacion_var6validado RESTART IDENTITY;
TRUNCATE horario_var6horario RESTART IDENTITY;
TRUNCATE diario_var6diario RESTART IDENTITY;
TRUNCATE mensual_var6mensual RESTART IDENTITY;
TRUNCATE anuarios_var6anuarios RESTART IDENTITY;

TRUNCATE medicion_var7medicion RESTART IDENTITY;
TRUNCATE validacion_var7validado RESTART IDENTITY;
TRUNCATE horario_var7horario RESTART IDENTITY;
TRUNCATE diario_var7diario RESTART IDENTITY;
TRUNCATE mensual_var7mensual RESTART IDENTITY;
TRUNCATE anuarios_var7anuarios RESTART IDENTITY;

TRUNCATE medicion_var8medicion RESTART IDENTITY;
TRUNCATE validacion_var8validado RESTART IDENTITY;
TRUNCATE horario_var8horario RESTART IDENTITY;
TRUNCATE diario_var8diario RESTART IDENTITY;
TRUNCATE mensual_var8mensual RESTART IDENTITY;
TRUNCATE anuarios_var8anuarios RESTART IDENTITY;

TRUNCATE medicion_var9medicion RESTART IDENTITY;
TRUNCATE validacion_var9validado RESTART IDENTITY;
TRUNCATE horario_var9horario RESTART IDENTITY;
TRUNCATE diario_var9diario RESTART IDENTITY;
TRUNCATE mensual_var9mensual RESTART IDENTITY;
TRUNCATE anuarios_var9anuarios RESTART IDENTITY;

TRUNCATE medicion_var10medicion RESTART IDENTITY;
TRUNCATE validacion_var10validado RESTART IDENTITY;
TRUNCATE horario_var10horario RESTART IDENTITY;
TRUNCATE diario_var10diario RESTART IDENTITY;
TRUNCATE mensual_var10mensual RESTART IDENTITY;
TRUNCATE anuarios_var10anuarios RESTART IDENTITY;

TRUNCATE medicion_var11medicion RESTART IDENTITY;
TRUNCATE validacion_var11validado RESTART IDENTITY;
TRUNCATE horario_var11horario RESTART IDENTITY;
TRUNCATE diario_var11diario RESTART IDENTITY;
TRUNCATE mensual_var11mensual RESTART IDENTITY;
TRUNCATE anuarios_var11anuarios RESTART IDENTITY;

TRUNCATE medicion_var12medicion RESTART IDENTITY;
TRUNCATE validacion_var12validado RESTART IDENTITY;
TRUNCATE horario_var12horario RESTART IDENTITY;
TRUNCATE diario_var12diario RESTART IDENTITY;
TRUNCATE mensual_var12mensual RESTART IDENTITY;

TRUNCATE medicion_var13medicion RESTART IDENTITY;
TRUNCATE validacion_var13validado RESTART IDENTITY;
TRUNCATE horario_var13horario RESTART IDENTITY;
TRUNCATE diario_var13diario RESTART IDENTITY;
TRUNCATE mensual_var13mensual RESTART IDENTITY;

TRUNCATE medicion_var14medicion RESTART IDENTITY;
TRUNCATE validacion_var14validado RESTART IDENTITY;
TRUNCATE horario_var14horario RESTART IDENTITY;
TRUNCATE diario_var14diario RESTART IDENTITY;
TRUNCATE mensual_var14mensual RESTART IDENTITY;

TRUNCATE medicion_var15medicion RESTART IDENTITY;
TRUNCATE validacion_var15validado RESTART IDENTITY;
TRUNCATE horario_var15horario RESTART IDENTITY;
TRUNCATE diario_var15diario RESTART IDENTITY;
TRUNCATE mensual_var15mensual RESTART IDENTITY;

TRUNCATE medicion_var16medicion RESTART IDENTITY;
TRUNCATE validacion_var16validado RESTART IDENTITY;
TRUNCATE horario_var16horario RESTART IDENTITY;
TRUNCATE diario_var16diario RESTART IDENTITY;
TRUNCATE mensual_var16mensual RESTART IDENTITY;

TRUNCATE medicion_var17medicion RESTART IDENTITY;
TRUNCATE validacion_var17validado RESTART IDENTITY;
TRUNCATE horario_var17horario RESTART IDENTITY;
TRUNCATE diario_var17diario RESTART IDENTITY;
TRUNCATE mensual_var17mensual RESTART IDENTITY;

TRUNCATE medicion_var18medicion RESTART IDENTITY;
TRUNCATE validacion_var18validado RESTART IDENTITY;
TRUNCATE horario_var18horario RESTART IDENTITY;
TRUNCATE diario_var18diario RESTART IDENTITY;
TRUNCATE mensual_var18mensual RESTART IDENTITY;

TRUNCATE medicion_var19medicion RESTART IDENTITY;
TRUNCATE validacion_var19validado RESTART IDENTITY;
TRUNCATE horario_var19horario RESTART IDENTITY;
TRUNCATE diario_var19diario RESTART IDENTITY;
TRUNCATE mensual_var19mensual RESTART IDENTITY;

TRUNCATE medicion_var20medicion RESTART IDENTITY;
TRUNCATE validacion_var20validado RESTART IDENTITY;
TRUNCATE horario_var20horario RESTART IDENTITY;
TRUNCATE diario_var20diario RESTART IDENTITY;
TRUNCATE mensual_var20mensual RESTART IDENTITY;

TRUNCATE medicion_var21medicion RESTART IDENTITY;
TRUNCATE validacion_var21validado RESTART IDENTITY;
TRUNCATE horario_var21horario RESTART IDENTITY;
TRUNCATE diario_var21diario RESTART IDENTITY;
TRUNCATE mensual_var21mensual RESTART IDENTITY;

TRUNCATE medicion_var22medicion RESTART IDENTITY;
TRUNCATE validacion_var22validado RESTART IDENTITY;
TRUNCATE horario_var22horario RESTART IDENTITY;
TRUNCATE diario_var22diario RESTART IDENTITY;
TRUNCATE mensual_var22mensual RESTART IDENTITY;

TRUNCATE medicion_var23medicion RESTART IDENTITY;
TRUNCATE validacion_var23validado RESTART IDENTITY;
TRUNCATE horario_var23horario RESTART IDENTITY;
TRUNCATE diario_var23diario RESTART IDENTITY;
TRUNCATE mensual_var23mensual RESTART IDENTITY;

TRUNCATE medicion_var24medicion RESTART IDENTITY;
TRUNCATE validacion_var24validado RESTART IDENTITY;
TRUNCATE horario_var24horario RESTART IDENTITY;
TRUNCATE diario_var24diario RESTART IDENTITY;
TRUNCATE mensual_var24mensual RESTART IDENTITY;

TRUNCATE medicion_var101medicion RESTART IDENTITY;
TRUNCATE validacion_var101validado RESTART IDENTITY;
TRUNCATE horario_var101horario RESTART IDENTITY;
TRUNCATE diario_var101diario RESTART IDENTITY;
TRUNCATE mensual_var101mensual RESTART IDENTITY;

TRUNCATE medicion_var102medicion RESTART IDENTITY;
TRUNCATE validacion_var102validado RESTART IDENTITY;
TRUNCATE horario_var102horario RESTART IDENTITY;
TRUNCATE diario_var102diario RESTART IDENTITY;
TRUNCATE mensual_var102mensual RESTART IDENTITY;

TRUNCATE medicion_var103medicion RESTART IDENTITY;
TRUNCATE validacion_var103validado RESTART IDENTITY;
TRUNCATE horario_var103horario RESTART IDENTITY;
TRUNCATE diario_var103diario RESTART IDENTITY;
TRUNCATE mensual_var103mensual RESTART IDENTITY;

TRUNCATE medicion_var104medicion RESTART IDENTITY;
TRUNCATE validacion_var104validado RESTART IDENTITY;
TRUNCATE horario_var104horario RESTART IDENTITY;
TRUNCATE diario_var104diario RESTART IDENTITY;
TRUNCATE mensual_var104mensual RESTART IDENTITY;

TRUNCATE medicion_var105medicion RESTART IDENTITY;
TRUNCATE validacion_var105validado RESTART IDENTITY;
TRUNCATE horario_var105horario RESTART IDENTITY;
TRUNCATE diario_var105diario RESTART IDENTITY;
TRUNCATE mensual_var105mensual RESTART IDENTITY;

TRUNCATE medicion_var106medicion RESTART IDENTITY;
TRUNCATE validacion_var106validado RESTART IDENTITY;
TRUNCATE horario_var106horario RESTART IDENTITY;
TRUNCATE diario_var106diario RESTART IDENTITY;
TRUNCATE mensual_var106mensual RESTART IDENTITY;

TRUNCATE medicion_var107medicion RESTART IDENTITY;
TRUNCATE validacion_var107validado RESTART IDENTITY;
TRUNCATE horario_var107horario RESTART IDENTITY;
TRUNCATE diario_var107diario RESTART IDENTITY;
TRUNCATE mensual_var107mensual RESTART IDENTITY;

TRUNCATE medicion_var108medicion RESTART IDENTITY;
TRUNCATE validacion_var108validado RESTART IDENTITY;
TRUNCATE horario_var108horario RESTART IDENTITY;
TRUNCATE diario_var108diario RESTART IDENTITY;
TRUNCATE mensual_var108mensual RESTART IDENTITY;