# Generated by Django 3.2.14 on 2023-06-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validated", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precipitation",
            name="total",
        ),
        migrations.AddField(
            model_name="precipitation",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Value"
            ),
        ),
    ]
