# Generated by Django 3.2.14 on 2023-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validated", "0004_auto_20230621_0216"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_a_used_fo_65ff0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["station_id", "time"], name="validated_a_station_efd012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["time", "station_id"], name="validated_a_time_6a8658_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_a_used_fo_c6296e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["station_id", "time"], name="validated_a_station_02ede4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["time", "station_id"], name="validated_a_time_2d5004_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_b_used_fo_49f172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["station_id", "time"], name="validated_b_station_729a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["time", "station_id"], name="validated_b_time_8638f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_f_used_fo_94cb49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["station_id", "time"], name="validated_f_station_be34bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["time", "station_id"], name="validated_f_time_888e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_f_used_fo_3ed969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["station_id", "time"], name="validated_f_station_c82cc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["time", "station_id"], name="validated_f_time_205834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_h_used_fo_a0366c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["station_id", "time"], name="validated_h_station_027b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["time", "station_id"], name="validated_h_time_27583f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_i_used_fo_2bab22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["station_id", "time"], name="validated_i_station_de5a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["time", "station_id"], name="validated_i_time_ea8637_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_p_used_fo_920bec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["station_id", "time"], name="validated_p_station_4d3055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["time", "station_id"], name="validated_p_time_07b89d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_s_used_fo_de6ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["station_id", "time"], name="validated_s_station_5ae709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["time", "station_id"], name="validated_s_time_9b89a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_s_used_fo_36617c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["station_id", "time"], name="validated_s_station_06d209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["time", "station_id"], name="validated_s_time_5f05b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_s_used_fo_1aa108_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["station_id", "time"], name="validated_s_station_fafad2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["time", "station_id"], name="validated_s_time_07daef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_w_used_fo_6b0e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["station_id", "time"], name="validated_w_station_f4ca00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["time", "station_id"], name="validated_w_time_1364a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_w_used_fo_4da0ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["station_id", "time"], name="validated_w_station_77efdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["time", "station_id"], name="validated_w_time_7bdfad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_w_used_fo_05b352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["station_id", "time"], name="validated_w_station_a8734f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["time", "station_id"], name="validated_w_time_0ecb07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["used_for_hourly"], name="validated_w_used_fo_777ff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["station_id", "time"], name="validated_w_station_5a54f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["time", "station_id"], name="validated_w_time_471880_idx"
            ),
        ),
    ]
