# Generated by Django 2.0.3 on 2018-07-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('variable', '0001_initial'),
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('aso_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('aso_id',),
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cla_valor', models.IntegerField(verbose_name='Columna valor')),
                ('cla_maximo', models.IntegerField(blank=True, null=True, verbose_name='Columna valor máximo')),
                ('cla_minimo', models.IntegerField(blank=True, null=True, verbose_name='Columna valor mínimo')),
            ],
            options={
                'ordering': ('var_id',),
            },
        ),
        migrations.CreateModel(
            name='Delimitador',
            fields=[
                ('del_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('del_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('del_caracter', models.CharField(max_length=5, verbose_name='Caracter')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('ext_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ext_valor', models.CharField(max_length=5, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('fec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fec_formato', models.CharField(max_length=20, verbose_name='Formato')),
                ('fec_codigo', models.CharField(max_length=20, verbose_name='Código')),
            ],
            options={
                'ordering': ('fec_id',),
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('for_id', models.AutoField(primary_key=True, serialize=False)),
                ('for_nombre', models.CharField(max_length=50, verbose_name='Nombre del Formato')),
                ('for_descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('for_ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('for_archivo', models.CharField(blank=True, help_text='Solo aplica para transmisión automática', max_length=100, null=True, verbose_name='Archivo')),
                ('for_fil_ini', models.IntegerField(verbose_name='Fila de inicio')),
                ('for_col_fecha', models.IntegerField(verbose_name='Columna fecha')),
                ('for_col_hora', models.IntegerField(verbose_name='Columna de hora')),
                ('for_tipo', models.CharField(choices=[('automatico', 'automático'), ('convencional', 'convencional'), ('ftp', 'ftp')], max_length=50, verbose_name='Tipo de Formato')),
                ('for_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('del_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Delimitador', verbose_name='Delimitador')),
                ('ext_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Extension', verbose_name='Extensión del Archivo')),
                ('fec_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Fecha', verbose_name='Formato de Fecha')),
            ],
            options={
                'ordering': ('for_id',),
            },
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('hor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('hor_formato', models.CharField(max_length=20, verbose_name='Formato')),
                ('hor_codigo', models.CharField(max_length=20, verbose_name='Código')),
            ],
            options={
                'ordering': ('hor_id',),
            },
        ),
        migrations.AddField(
            model_name='formato',
            name='hor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Hora', verbose_name='Formato de Hora'),
        ),
        migrations.AddField(
            model_name='formato',
            name='mar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='for_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formato.Formato', verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='var_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variable.Variable', verbose_name='Variable'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='for_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato'),
        ),
    ]
