# Generated by Django 2.1.1 on 2019-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0002_auto_20180905_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='acumular',
            field=models.BooleanField(default=False, verbose_name='¿Acumular a 5 minutos?'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='col_validador_maximo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Columna validador Máximo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='col_validador_minimo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Columna validador Mínimo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='col_validador_valor',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Columna validador Valor'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='coma_decimal',
            field=models.BooleanField(default=False, verbose_name='COMA: separador decimal'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='incremental',
            field=models.BooleanField(default=False, verbose_name='¿Es contador incremental?'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='resolucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='txt_validador_maximo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Texto validador Máximo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='txt_validador_minimo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Texto validador Mínimo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='txt_validador_valor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Texto validador Valor'),
        ),
        migrations.AddField(
            model_name='formato',
            name='for_fil_cola',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Número de filas de cola'),
        ),
    ]
