# Generated by Django 2.2.1 on 2020-04-03 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
                ('mes_seco', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='mes seco')),
                ('mes_seco_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('mes_lluvioso', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='mes lluvioso')),
                ('mes_lluvioso_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('dias_con_lluvia', models.IntegerField(null=True, verbose_name='dias con lluvia')),
                ('dias_sin_lluvia', models.IntegerField(null=True, verbose_name='dias sin lluvia')),
                ('estacionalidad', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='estacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=7, max_digits=15, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_veloc_fecha_8c3df1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='velocidadviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_tempe_fecha_c48297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_tempe_fecha_2cd5b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_radia_fecha_59b1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiacionsolar',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_presi_fecha_d76a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presionatmosferica',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_preci_fecha_74667c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_humed_fecha_711dc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadsuelo',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_humed_fecha_e5ebad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_direc_fecha_e482ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direccionviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='anual_cauda_fecha_51bf27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
