# Generated by Django 3.0.4 on 2020-03-31 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitacion',
            name='dias_con_lluvia',
            field=models.IntegerField(null=True, verbose_name='dias con lluvia'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='dias_sin_lluvia',
            field=models.IntegerField(null=True, verbose_name='dias sin lluvia'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='estacionalidad',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='estacionalidad'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='mes_lluvioso',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='mes lluvioso'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='mes_lluvioso_valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='mes_seco',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='mes seco'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='mes_seco_valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
