# Generated by Django 3.0.4 on 2020-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anual', '0002_auto_20200322_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitacion',
            name='mes_lluvioso_valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='mes_seco_valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
