# Generated by Django 3.0.4 on 2020-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anual', '0003_auto_20200325_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitacion',
            name='estacionalidad',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='estacionalidad'),
        ),
    ]
