# Generated by Django 3.2.14 on 2023-06-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily", "0005_auto_20230621_0111"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_airte_used_fo_08676f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["station_id", "time"], name="daily_airte_station_78d525_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["time", "station_id"], name="daily_airte_time_2de4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_atmos_used_fo_610b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["station_id", "time"], name="daily_atmos_station_b0bd63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["time", "station_id"], name="daily_atmos_time_73e2b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_batte_used_fo_5de6ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["station_id", "time"], name="daily_batte_station_9949ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["time", "station_id"], name="daily_batte_time_5d8bc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_flow_used_fo_44c435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["station_id", "time"], name="daily_flow_station_726fec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["time", "station_id"], name="daily_flow_time_235667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_flowm_used_fo_e56e8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["station_id", "time"], name="daily_flowm_station_f6cfa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["time", "station_id"], name="daily_flowm_time_6b81cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_humid_used_fo_b73334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["station_id", "time"], name="daily_humid_station_2defbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["time", "station_id"], name="daily_humid_time_2fd59d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_indir_used_fo_70768f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["station_id", "time"], name="daily_indir_station_92b0bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["time", "station_id"], name="daily_indir_time_5c5c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_preci_used_fo_ea2724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["station_id", "time"], name="daily_preci_station_a10efa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["time", "station_id"], name="daily_preci_time_565d6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_soilm_used_fo_fc54af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["station_id", "time"], name="daily_soilm_station_ca0156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["time", "station_id"], name="daily_soilm_time_8834fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_soilt_used_fo_c3e3aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["station_id", "time"], name="daily_soilt_station_5f6764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["time", "station_id"], name="daily_soilt_time_46a4f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_solar_used_fo_e5d3f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["station_id", "time"], name="daily_solar_station_3fe013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["time", "station_id"], name="daily_solar_time_24df42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_water_used_fo_0ec7bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["station_id", "time"], name="daily_water_station_189cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["time", "station_id"], name="daily_water_time_931962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_water_used_fo_4026fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["station_id", "time"], name="daily_water_station_4c8b96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["time", "station_id"], name="daily_water_time_b76f44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_windd_used_fo_5efe03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["station_id", "time"], name="daily_windd_station_dfb1fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["time", "station_id"], name="daily_windd_time_da3957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["used_for_monthly"], name="daily_windv_used_fo_080fc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["station_id", "time"], name="daily_windv_station_e7a0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["time", "station_id"], name="daily_windv_time_574a5c_idx"
            ),
        ),
    ]
