# Generated by Django 2.0.3 on 2018-04-19 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('est_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('est_tipo', models.CharField(choices=[('M', 'Meteorológica'), ('P', 'Pluviométrica'), ('H', 'Hidrológica')], max_length=25, verbose_name='Tipo')),
                ('est_estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('est_provincia', models.CharField(max_length=50, null=True, verbose_name='Provincia')),
                ('est_latitud', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Latitud')),
                ('est_longitud', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Longitud')),
                ('est_altura', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(6000), django.core.validators.MinValueValidator(0)], verbose_name='Altura')),
                ('est_ficha', models.FileField(upload_to='documents/', verbose_name='Fichas')),
            ],
            options={
                'ordering': ('est_id',),
            },
        ),
    ]
