# Generated by Django 2.1.1 on 2019-05-15 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('est_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('est_estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('est_latitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud')),
                ('est_longitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitud')),
                ('est_utmy', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Y UTM')),
                ('est_utmx', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='X UTM')),
                ('est_altura', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(6000), django.core.validators.MinValueValidator(0)], verbose_name='Altura')),
                ('est_ficha', models.FileField(upload_to='documents/', verbose_name='Fichas')),
                ('est_fecha_inicio', models.DateField(null=True, verbose_name='Fecha Inicio Operaciones')),
            ],
            options={
                'ordering': ('est_id',),
            },
        ),
        migrations.CreateModel(
            name='Inamhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(verbose_name='Id')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('transmision', models.CharField(max_length=100, verbose_name='Transmision')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitud')),
                ('provincia', models.CharField(max_length=50, verbose_name='Nombre')),
                ('canton', models.CharField(max_length=50, verbose_name='Cantón')),
                ('parroquia', models.CharField(max_length=50, verbose_name='Parroquia')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.Tipo', verbose_name='Tipo'),
        ),
    ]
