# Generated by Django 2.0.3 on 2018-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
