# Generated by Django 2.0.3 on 2018-08-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0002_provincia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='est_fecha_inicio',
            field=models.DateField(null=True, verbose_name='Fecha Inicio Operaciones'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.Tipo', verbose_name='Tipo'),
        ),
    ]
