# Generated by Django 2.0.3 on 2018-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0003_auto_20180803_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='est_provincia',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='est_tipo',
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_latitud',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Y UTM'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_longitud',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='X UTM'),
        ),
    ]
