# Generated by Django 2.1.1 on 2019-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0004_auto_20180814_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='est_utmx',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='X UTM'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='est_utmy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Y UTM'),
        ),
    ]
