# Generated by Django 2.1.1 on 2019-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0008_auto_20190321_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='est_latitud',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_longitud',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitud'),
        ),
    ]
