# Generated by Django 2.1.1 on 2019-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0009_auto_20190321_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inamhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(verbose_name='Id')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('transmision', models.CharField(max_length=100, verbose_name='Transmision')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='Longitud')),
                ('provincia', models.CharField(max_length=50, verbose_name='Nombre')),
                ('canton', models.CharField(max_length=50, verbose_name='Cantón')),
                ('parroquia', models.CharField(max_length=50, verbose_name='Parroquia')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
    ]
