# Generated by Django 2.2.1 on 2019-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0010_inamhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='transmision',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Trasmision'),
        ),
    ]
