# Generated by Django 2.2.1 on 2019-11-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0011_estacion_transmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=40)),
                ('imagen', models.FileField(null=True, upload_to='estacion/cuenca_imagen/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=40)),
                ('imagen', models.FileField(null=True, upload_to='estacion/sistema_imagen/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='estacion',
            name='est_externa',
            field=models.BooleanField(default=True, verbose_name='Externa'),
        ),
        migrations.CreateModel(
            name='SistemaCuenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('imagen', models.FileField(null=True, upload_to='estacion/sistemacuenca_imagen/', verbose_name='Imagen')),
                ('cuenca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Cuenca', verbose_name='Cuenca')),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Sistema', verbose_name='Sistema')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('sistema', 'cuenca')},
            },
        ),
        migrations.AddField(
            model_name='estacion',
            name='sistemacuenca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.SistemaCuenca', verbose_name='SistemaCuenca'),
        ),
    ]
