# Generated by Django 2.2.1 on 2019-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0012_auto_20191105_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='influencia_km',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Infuencia km'),
        ),
    ]
