# Generated by Django 2.2.1 on 2020-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0013_estacion_influencia_km'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ('est_externa', 'est_codigo')},
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_estado',
            field=models.BooleanField(default=True, help_text='Desmarcar si la estación ya no opera', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_externa',
            field=models.BooleanField(default=True, help_text='Marcar si la estación es de la EPMAPS', verbose_name='Externa'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='influencia_km',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Área de Aporte (km)'),
        ),
    ]
