# Generated by Django 3.2.14 on 2023-04-15 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=25, verbose_name='Brand name')),
            ],
            options={
                'ordering': ('brand_id',),
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=25, verbose_name='Sensor type')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(max_length=32, null=True, unique=True, verbose_name='Code')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Model')),
                ('serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('status', models.BooleanField(default=False, verbose_name='Status (active)')),
                ('sensor_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensorbrand', verbose_name='Sensor brand')),
                ('sensor_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensortype', verbose_name='Sensor type')),
            ],
            options={
                'ordering': ('code', 'sensor_type', 'sensor_brand', 'model'),
            },
        ),
    ]
