# Generated by Django 3.0.11 on 2022-07-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorBrand",
            fields=[
                (
                    "brand_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Brand name")),
            ],
            options={
                "ordering": ("brand_id",),
            },
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "type_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Sensor type")),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "sensor_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, null=True, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Model"
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Serial number",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Status (active)"),
                ),
                (
                    "sensor_brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensor.SensorBrand",
                        verbose_name="Sensor brand",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensor.SensorType",
                        verbose_name="Sensor type",
                    ),
                ),
            ],
            options={
                "ordering": ("code", "sensor_type", "sensor_brand", "model"),
            },
        ),
    ]
