# Generated by Django 2.1.1 on 2019-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sen_codigo', models.CharField(max_length=20, null=True, verbose_name='Codigo')),
                ('sen_modelo', models.CharField(max_length=150, null=True, verbose_name='Modelo')),
                ('sen_serial', models.CharField(max_length=20, null=True, verbose_name='Serial')),
                ('sen_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('mar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca')),
            ],
            options={
                'ordering': ('sen_codigo', 'tipo', 'sen_modelo', 'sen_serial'),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nombre', models.CharField(max_length=25, verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.Tipo', verbose_name='Tipo'),
        ),
    ]
