# Generated by Django 2.0.3 on 2018-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sen_codigo',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_nombre',
            field=models.CharField(choices=[('Dirección del viento', 'Dirección del viento'), ('Humedad y Temperatura', 'Humedad y Temperatura'), ('Pluviómetro', 'Pluviómetro'), ('Presión Barométrica', 'Presión Barométrica'), ('Radiación Solar', 'Radiación Solar'), ('Sensor de viento', 'Sensor de viento'), ('Sonda Piezométrico', 'Sonda Piezométrico'), ('Sonda Ultrasónico', 'Sonda Ultrasónico'), ('Velocidad del viento', 'Velocidad del viento')], max_length=40, verbose_name='Nombre'),
        ),
    ]
