# Generated by Django 2.0.3 on 2018-09-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nombre', models.CharField(max_length=25, verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.Tipo', verbose_name='Tipo'),
        ),
    ]
