# Generated by Django 2.0.3 on 2018-09-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20180905_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('sen_codigo', 'tipo', 'sen_modelo', 'sen_serial')},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sen_nombre',
        ),
    ]
