# Generated by Django 2.0.3 on 2018-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20180419_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sen_modelo',
            field=models.CharField(max_length=150, null=True, verbose_name='Modelo'),
        ),
    ]
