# Generated by Django 2.0.3 on 2018-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20180905_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sen_codigo',
            field=models.CharField(max_length=20, null=True, verbose_name='Codigo'),
        ),
    ]
