# Generated by Django 5.0.3 on 2024-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0004_alter_sensor_owner_alter_sensor_sensor_brand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="permissions_level",
            new_name="visibility",
        ),
        migrations.RenameField(
            model_name="sensorbrand",
            old_name="permissions_level",
            new_name="visibility",
        ),
        migrations.RenameField(
            model_name="sensortype",
            old_name="permissions_level",
            new_name="visibility",
        ),
    ]
