# Generated by Django 5.1 on 2024-09-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0005_rename_permissions_level_sensor_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sensor.sensorbrand",
                verbose_name="Sensor brand",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sensor.sensortype",
                verbose_name="Sensor type",
            ),
        ),
    ]
