# Generated by Django 5.1.1 on 2024-10-10 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_alter_sensor_code_alter_sensor_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensorbrand',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
