# Generated by Django 2.2.1 on 2019-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
                ('usado_para_anual', models.BooleanField(default=False, verbose_name='Usado para anual')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('usado_para_anual', models.BooleanField(default=False, verbose_name='Usado para anual')),
                ('max_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='maximo valor en el dia')),
                ('max_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del maximo')),
                ('min_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='minimo valor en el dia')),
                ('min_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del minimo')),
                ('prom_mes', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Promedio del mes')),
                ('quan10', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='cuantil 10')),
                ('quan95', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='cuantil 95')),
                ('dias0', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dias sin lluvia')),
                ('dias01', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dias lluvias de 0.1')),
            ],
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='estames_pre_fecha_272946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='estames_cau_fecha_0fddf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
