# Generated by Django 3.2.14 on 2023-04-15 03:19

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolarWind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('speed', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Speed')),
                ('direction', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Direction')),
            ],
            options={
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AirTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtmosphericPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChlorineConcentrationDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('value', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndirectRadiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OxygenConcentrationDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PercentageOxygenConcentrationDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PhycocyaninDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Total')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedoxPotentialDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoilTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarRadiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripLevelReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('value', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Value')),
                ('uncertainty', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Uncertainty')),
                ('data_import_date', models.DateTimeField(verbose_name='Data import date')),
                ('data_start_date', models.DateTimeField(verbose_name='Data start date')),
                ('calibrated', models.BooleanField(verbose_name='Calibrated')),
                ('comments', models.CharField(max_length=250, null=True, verbose_name='Comments')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WaterAcidityDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTemperatureDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WaterTurbidityDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='e')),
                ('depth', models.PositiveSmallIntegerField(verbose_name='Depth')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindVelocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('date', models.DateField(verbose_name='date')),
                ('station_id', models.PositiveIntegerField(verbose_name='station_id')),
                ('completeness', models.DecimalField(decimal_places=1, max_digits=4)),
                ('v', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='v')),
                ('r', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='r')),
                ('a', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='a')),
                ('g', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='g')),
                ('e', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='waterturbiditydepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_wat_station_202485_idx'),
        ),
        migrations.AddIndex(
            model_name='watertemperaturedepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_wat_station_8be936_idx'),
        ),
        migrations.AddIndex(
            model_name='wateraciditydepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_wat_station_06480a_idx'),
        ),
        migrations.AddIndex(
            model_name='striplevelreading',
            index=models.Index(fields=['station_id', 'data_import_date'], name='monthly_str_station_8b7a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='striplevelreading',
            index=models.Index(fields=['station_id', 'data_start_date', 'time'], name='monthly_str_station_c0561a_idx'),
        ),
        migrations.AddIndex(
            model_name='striplevelreading',
            index=models.Index(fields=['data_import_date'], name='monthly_str_data_im_277dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='redoxpotentialdepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_red_station_4a35df_idx'),
        ),
        migrations.AddIndex(
            model_name='phycocyanindepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_phy_station_847000_idx'),
        ),
        migrations.AddIndex(
            model_name='percentageoxygenconcentrationdepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_per_station_d1f852_idx'),
        ),
        migrations.AddIndex(
            model_name='oxygenconcentrationdepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_oxy_station_4c4c64_idx'),
        ),
        migrations.AddIndex(
            model_name='chlorineconcentrationdepth',
            index=models.Index(fields=['station_id', 'depth', 'time'], name='monthly_chl_station_18483d_idx'),
        ),
    ]
