# Generated by Django 3.2.14 on 2023-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monthly", "0005_auto_20230621_0111"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_air_station_a5ddff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_air_time_129a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_atm_station_c95cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_atm_time_1c3886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_bat_station_b8fa32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_bat_time_0cfe86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_flo_station_8e046b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_flo_time_443707_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_flo_station_2736af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_flo_time_867de9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_hum_station_8172f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_hum_time_e00ec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_ind_station_3983db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_ind_time_b81cce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_pre_station_071298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_pre_time_53a31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_soi_station_07b8d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_soi_time_b2e69d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_soi_station_8e9ea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_soi_time_a9f612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_sol_station_65c309_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_sol_time_d0b2a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_wat_station_4f4b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_wat_time_ddc003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_wat_station_4293a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_wat_time_abfcea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_win_station_375494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_win_time_027619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["station_id", "time"], name="monthly_win_station_826aa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["time", "station_id"], name="monthly_win_time_9b76fe_idx"
            ),
        ),
    ]
