# Generated by Django 2.1.1 on 2019-05-15 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variable', '0001_initial'),
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('fre_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fre_valor', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(0)], verbose_name='Frecuencia (min)')),
                ('fre_fecha_ini', models.DateField(verbose_name='Fecha inicio')),
                ('fre_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
        ),
    ]
