# Generated by Django 2.2.1 on 2020-02-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frecuencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frecuencia',
            options={'ordering': ('fre_id',)},
        ),
    ]
