################################################################################################
# Plataforma para la Iniciativa Regional de Monitoreo Hidrológico de Ecosistemas Andinos (iMHEA)
# basada en los desarrollos realizados por:
#     1) FONDO PARA LA PROTECCIÓN DEL AGUA (FONAG), Ecuador.
#         Contacto: info@fonag.org.ec
#     2) EMPRESA PÚBLICA METROPOLITANA DE AGUA POTABLE Y SANEAMIENTO DE QUITO (EPMAPS), Ecuador.
#         Contacto: paramh2o@aguaquito.gob.ec
#
#  IMPORTANTE: Mantener o incluir esta cabecera con la mención de las instituciones creadoras,
#              ya sea en uso total o parcial del código.

"""
Django settings for djangomain project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 15000000

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mj7(ja+=@-xxx&(t)_2um%y^khe17txt&^_ydw0d168%+so#yd'

# SECURITY WARNING: don't run with debug turned on in production!

#DEBUG = False
DEBUG = True
ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['127.0.0.1', ]

# DEBUG = False
# ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'estacion.apps.EstacionConfig',
    'datalogger.apps.DataloggerConfig',
    'sensor.apps.SensorConfig',
    'variable.apps.VariableConfig',
    'bitacora.apps.BitacoraConfig',
    'cruce.apps.CruceConfig',
    'formato.apps.FormatoConfig',
    'frecuencia.apps.FrecuenciaConfig',
    'instalacion.apps.InstalacionConfig',
    'medicion.apps.MedicionConfig',
    'validacion.apps.ValidacionConfig',
    'validacion_v2.apps.ValidacionV2Config',
    'horario.apps.HorarioConfig',
    'diario.apps.DiarioConfig',
    'mensual.apps.MensualConfig',
    'importacion.apps.ImportacionConfig',
    'vacios.apps.VaciosConfig',
    'calidad.apps.CalidadConfig',
    'reportes.apps.ReportesConfig',
    'reportes_v2.apps.Reportes_v2Config',
    'telemetria.apps.TelemetriaConfig',
    'anual.apps.AnualConfig',
    'indices.apps.IndicesConfig',
    'anuarios.apps.AnuariosConfig',
    'bootstrap4',
    'django_extensions',
    'django.contrib.humanize',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #
    # 'debug_toolbar',
    #
]

MIDDLEWARE = [
    ##
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    ##
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangomain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                ##
                'home.context_processor.menu',
                ##

            ],
        },
    },
]

WSGI_APPLICATION = 'djangomain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'imhea',
        'USER': 'imhea',
        'PASSWORD': 'imhea',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_L10N = True
# USE_TZ = True

LANGUAGE_CODE = 'es-EC'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_L10N = False
DECIMAL_SEPARATOR = '.'
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [  # Directorios adicionales static
    os.path.join(BASE_DIR, "static"),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

INTERNAL_IPS = ('127.0.0.1',)


########################################################################

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

########################################################################
# Requerido para enviar mensajes de correo a través de servidor SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '10.1.1.18'
EMAIL_PORT = 25
#
#########################################################################

#########################################################################
# Implementa permisos para usuario Anónimo
#
# Reemplaza a:
#              AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
AUTHENTICATION_BACKENDS = ['home.auth_backend.AnonymousPermissions']
#
#########################################################################