# Generated by Django 2.2.1 on 2020-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
                ('usado_para_anual', models.BooleanField(default=False, null=True, verbose_name='Usado para anual')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
                ('usado_para_anual', models.BooleanField(default=False, null=True, verbose_name='Usado para anual')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=7, max_digits=15, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=7, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('max_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo del promedio')),
                ('min_del_prom', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo del promedio')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('completo_umbral', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo Umbral %')),
            ],
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_vel_fecha_f9785f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='velocidadviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_tem_fecha_f97f86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_tem_fecha_77d6b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_rad_fecha_e7b6ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiacionsolar',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_pre_fecha_a7d27d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presionatmosferica',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_pre_fecha_480502_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_niv_fecha_a29de0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivelagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_hum_fecha_4c4d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadsuelo',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_hum_fecha_a0b107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_dir_fecha_c193f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direccionviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='mensual_cau_fecha_7dc069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
