# Generated by Django 2.2.1 on 2020-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caudal',
            name='usado_para_anual',
            field=models.BooleanField(default=False, null=True, verbose_name='Usado para anual'),
        ),
        migrations.AddField(
            model_name='precipitacion',
            name='usado_para_anual',
            field=models.BooleanField(default=False, null=True, verbose_name='Usado para anual'),
        ),
    ]
