# Generated by Django 2.2.1 on 2020-03-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0014_auto_20200310_1629'),
        ('variable', '0011_auto_20191108_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitacionAcumulada',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecipitacionAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecipitacionEventos',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecipitacionMultianual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmaEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaTipoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeleVariables',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVisualizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_superior', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Umbral superior')),
                ('umbral_inferior', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Umbral inferior')),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telemetria.AlarmaTipoEstado')),
            ],
        ),
        migrations.AddIndex(
            model_name='configvisualizar',
            index=models.Index(fields=['variable', 'estacion'], name='telemetria__variabl_280e5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configvisualizar',
            unique_together={('estacion', 'variable')},
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['estacion', 'estado', 'fecha'], name='telemetria__estacio_db2b61_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['estacion', 'fecha', 'estado'], name='telemetria__estacio_aa25e0_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['estado', 'estacion', 'fecha'], name='telemetria__estado__2760ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['estado', 'fecha', 'estacion'], name='telemetria__estado__ec0862_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['fecha', 'estacion', 'estado'], name='telemetria__fecha_e8754a_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmaestado',
            index=models.Index(fields=['fecha', 'estado', 'estacion'], name='telemetria__fecha_adf33a_idx'),
        ),
    ]
