# Generated by Django 2.2.1 on 2020-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmaestado',
            name='fecha_dato',
            field=models.DateTimeField(null=True),
        ),
    ]
