from django.urls import path

from .views import (
    ClassificationCreateView,
    ClassificationDeleteView,
    ClassificationDetailView,
    ClassificationEditView,
    DateCreateView,
    DateDeleteView,
    DateDetailView,
    DateEditView,
    DelimiterCreateView,
    DelimiterDeleteView,
    DelimiterDetailView,
    DelimiterEditView,
    ExtensionCreateView,
    ExtensionDeleteView,
    ExtensionDetailView,
    ExtensionEditView,
    FormatCreateView,
    FormatDeleteView,
    FormatDetailView,
    FormatEditView,
    TimeCreateView,
    TimeDeleteView,
    TimeDetailView,
    TimeEditView,
)

app_name = "formatting"
urlpatterns = [
    path("extension/<int:pk>", ExtensionDetailView.as_view(), name="extension_detail"),
    path("delimiter/<int:pk>", DelimiterDetailView.as_view(), name="delimiter_detail"),
    path("date/<int:pk>", DateDetailView.as_view(), name="date_detail"),
    path("time/<int:pk>", TimeDetailView.as_view(), name="time_detail"),
    path("format/<int:pk>", FormatDetailView.as_view(), name="format_detail"),
    path(
        "classification/<int:pk>",
        ClassificationDetailView.as_view(),
        name="classification_detail",
    ),
    path("extension/create/", ExtensionCreateView.as_view(), name="extension_create"),
    path("delimiter/create/", DelimiterCreateView.as_view(), name="delimiter_create"),
    path("date/create/", DateCreateView.as_view(), name="date_create"),
    path("time/create/", TimeCreateView.as_view(), name="time_create"),
    path("format/create/", FormatCreateView.as_view(), name="format_create"),
    path(
        "classification/create/",
        ClassificationCreateView.as_view(),
        name="classification_create",
    ),
    path("extension/edit/<int:pk>", ExtensionEditView.as_view(), name="extension_edit"),
    path("delimiter/edit/<int:pk>", DelimiterEditView.as_view(), name="delimiter_edit"),
    path("date/edit/<int:pk>", DateEditView.as_view(), name="date_edit"),
    path("time/edit/<int:pk>", TimeEditView.as_view(), name="time_edit"),
    path("format/edit/<int:pk>", FormatEditView.as_view(), name="format_edit"),
    path(
        "classification/edit/<int:pk>",
        ClassificationEditView.as_view(),
        name="classification_edit",
    ),
    path("date/delete/<int:pk>", DateDeleteView.as_view(), name="date_delete"),
    path(
        "delimiter/delete/<int:pk>",
        DelimiterDeleteView.as_view(),
        name="delimiter_delete",
    ),
    path(
        "extension/delete/<int:pk>",
        ExtensionDeleteView.as_view(),
        name="extension_delete",
    ),
    path("format/delete/<int:pk>", FormatDeleteView.as_view(), name="format_delete"),
    path("time/delete/<int:pk>", TimeDeleteView.as_view(), name="time_delete"),
    path(
        "classification/delete/<int:pk>",
        ClassificationDeleteView.as_view(),
        name="classification_delete",
    ),
]
