# Generated by Django 2.2.1 on 2019-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaGenericaFecha',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaGenericaFechaHora',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaGenericaFechaHoraGrafico',
            fields=[
                ('fila', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('salto', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
