# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('datalogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('ins_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ins_fecha_ini', models.DateField(verbose_name='Fecha de inicio')),
                ('ins_fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('ins_en_uso', models.BooleanField(default=True, verbose_name='En uso')),
                ('ins_observacion', models.CharField(blank=True, max_length=500, verbose_name='Observacion')),
                ('dat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalogger.Datalogger', verbose_name='Datalogger')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('ins_id', 'est_id', 'dat_id'),
            },
        ),
    ]
