# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('imp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('imp_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('imp_fecha_ini', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicial')),
                ('imp_fecha_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Final')),
                ('imp_archivo', models.FileField(upload_to='archivos/', verbose_name='Archivo')),
                ('imp_observacion', models.TextField(blank=True, default='Carga de Datos', null=True, verbose_name='Observaciones/Anotaciones')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('for_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('-imp_fecha',),
            },
        ),
    ]
