# Generated by Django 2.0.3 on 2018-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='imp_tipo',
            field=models.CharField(default='c', max_length=1, verbose_name='Tipo'),
        ),
    ]
