# Generated by Django 2.1.1 on 2019-02-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0004_auto_20180814_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formato', '0003_auto_20190211_1104'),
        ('importacion', '0002_importacion_imp_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionTemp',
            fields=[
                ('imp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('imp_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('imp_fecha_ini', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicial')),
                ('imp_fecha_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Final')),
                ('imp_archivo', models.FileField(upload_to='archivos/tmp/', verbose_name='Archivo')),
                ('imp_observacion', models.TextField(blank=True, default='Carga de Datos', null=True, verbose_name='Observaciones/Anotaciones')),
                ('imp_tipo', models.CharField(default='c', max_length=1, verbose_name='Tipo')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('for_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('-imp_fecha',),
            },
        ),
    ]
