# Generated by Django 2.1.1 on 2019-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('cau_id', models.AutoField(primary_key=True, serialize=False)),
                ('cau_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('cau_mes', models.IntegerField(verbose_name='Mes')),
                ('cau_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('cau_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('cau_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('cau_mes',),
            },
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('hai_id', models.AutoField(primary_key=True, serialize=False)),
                ('hai_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('hai_mes', models.IntegerField(verbose_name='Mes')),
                ('hai_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo Absoluto')),
                ('hai_maximo_dia', models.IntegerField(verbose_name='Día')),
                ('hai_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo Absoluto')),
                ('hai_minimo_dia', models.IntegerField(verbose_name='Día')),
                ('hai_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo Absoluto')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('hai_mes',),
            },
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('hsu_id', models.AutoField(primary_key=True, serialize=False)),
                ('hsu_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('hsu_mes', models.IntegerField(verbose_name='Mes')),
                ('hsu_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('hsu_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('hsu_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('hsu_mes',),
            },
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('nag_id', models.AutoField(primary_key=True, serialize=False)),
                ('nag_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('nag_mes', models.IntegerField(verbose_name='Mes')),
                ('nag_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('nag_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('nag_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('nag_mes',),
            },
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_periodo', models.IntegerField(verbose_name='Año')),
                ('pre_mes', models.IntegerField(verbose_name='Mes')),
                ('pre_suma', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precipitación')),
                ('pre_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo en 24H')),
                ('pre_maximo_dia', models.IntegerField(verbose_name='Día')),
                ('pre_dias', models.IntegerField(verbose_name='Total de días con precipitacion')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('pre_mes',),
            },
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('pat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('pat_mes', models.IntegerField(verbose_name='Mes')),
                ('pat_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('pat_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('pat_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('pat_mes',),
            },
        ),
        migrations.CreateModel(
            name='RadiacionMaxima',
            fields=[
                ('rad_id', models.AutoField(primary_key=True, serialize=False)),
                ('rad_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('rad_mes', models.IntegerField(verbose_name='Mes')),
                ('rad_5', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='5')),
                ('rad_6', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='6')),
                ('rad_7', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='7')),
                ('rad_8', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='8')),
                ('rad_9', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='9')),
                ('rad_10', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='10')),
                ('rad_11', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='11')),
                ('rad_12', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='12')),
                ('rad_13', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='13')),
                ('rad_14', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='14')),
                ('rad_15', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='15')),
                ('rad_16', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='16')),
                ('rad_17', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='17')),
                ('rad_18', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='18')),
                ('rad_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('rad_hora', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hora')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('rad_mes',),
            },
        ),
        migrations.CreateModel(
            name='RadiacionMinima',
            fields=[
                ('rad_id', models.AutoField(primary_key=True, serialize=False)),
                ('rad_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('rad_mes', models.IntegerField(verbose_name='Mes')),
                ('rad_5', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='5')),
                ('rad_6', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='6')),
                ('rad_7', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='7')),
                ('rad_8', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='8')),
                ('rad_9', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='9')),
                ('rad_10', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='10')),
                ('rad_11', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='11')),
                ('rad_12', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='12')),
                ('rad_13', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='13')),
                ('rad_14', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='14')),
                ('rad_15', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='15')),
                ('rad_16', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='16')),
                ('rad_17', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='17')),
                ('rad_18', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='18')),
                ('rad_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínima')),
                ('rad_hora', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hora')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('rad_mes',),
            },
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('rad_id', models.AutoField(primary_key=True, serialize=False)),
                ('rad_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('rad_mes', models.IntegerField(verbose_name='Mes')),
                ('rad_hora', models.IntegerField(verbose_name='Hora')),
                ('rad_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('rad_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('tag_mes', models.IntegerField(verbose_name='Mes')),
                ('tag_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('tag_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('tag_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('tag_mes',),
            },
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('tai_id', models.AutoField(primary_key=True, serialize=False)),
                ('tai_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('tai_mes', models.IntegerField(verbose_name='Mes')),
                ('tai_maximo_abs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo Absoluto')),
                ('tai_maximo_dia', models.IntegerField(verbose_name='Día')),
                ('tai_minimo_abs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo Absoluto')),
                ('tai_minimo_dia', models.IntegerField(verbose_name='Día')),
                ('tai_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Máximo')),
                ('tai_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Mínimo')),
                ('tai_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('tai_mes',),
            },
        ),
        migrations.CreateModel(
            name='Viento',
            fields=[
                ('vie_id', models.AutoField(primary_key=True, serialize=False)),
                ('vie_periodo', models.IntegerField(default=2000, verbose_name='Año')),
                ('vie_mes', models.IntegerField(verbose_name='Mes')),
                ('vie_vel_N', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Norte')),
                ('vie_por_N', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Norte')),
                ('vie_vel_NE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Noreste')),
                ('vie_por_NE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Noreste')),
                ('vie_vel_E', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Este')),
                ('vie_por_E', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Este')),
                ('vie_vel_SE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Sureste')),
                ('vie_por_SE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Sureste')),
                ('vie_vel_S', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Sur')),
                ('vie_por_S', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Sur')),
                ('vie_vel_SO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Suroeste')),
                ('vie_por_SO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Suroeste')),
                ('vie_vel_O', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Oeste')),
                ('vie_por_O', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Oeste')),
                ('vie_vel_NO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Noroeste')),
                ('vie_por_NO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Noroeste')),
                ('vie_calma', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Calma')),
                ('vie_obs', models.IntegerField(default=2000, verbose_name='Numero de Observaciones')),
                ('vie_vel_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Velocidad Mayor m/s')),
                ('vie_vel_dir', models.CharField(max_length=2, verbose_name='Dirección Velocidad Mayor')),
                ('vie_vel_med', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Velocidad Media Km/h')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
            ],
            options={
                'ordering': ('vie_mes',),
            },
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['est_id', 'vie_periodo'], name='anuarios_vi_est_id__622a42_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['est_id', 'tai_periodo'], name='anuarios_te_est_id__dc1e12_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['est_id', 'tag_periodo'], name='anuarios_te_est_id__9a458c_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionminima',
            index=models.Index(fields=['est_id', 'rad_periodo'], name='anuarios_ra_est_id__eb906c_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionmaxima',
            index=models.Index(fields=['est_id', 'rad_periodo'], name='anuarios_ra_est_id__9377cd_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['est_id', 'pat_periodo'], name='anuarios_pr_est_id__0a28a0_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['est_id', 'pre_periodo'], name='anuarios_pr_est_id__c2de2f_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['est_id', 'nag_periodo'], name='anuarios_ni_est_id__61240e_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['est_id', 'hsu_periodo'], name='anuarios_hu_est_id__3d3ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['est_id', 'hai_periodo'], name='anuarios_hu_est_id__2d9ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['est_id', 'cau_periodo'], name='anuarios_ca_est_id__2b4a97_idx'),
        ),
    ]
