# Generated by Django 2.1.1 on 2019-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['est_id', 'pre_periodo'], name='anuarios_pr_est_id__c2de2f_idx'),
        ),
    ]
