# Generated by Django 2.1.1 on 2019-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuarios', '0002_auto_20190208_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precipitacion',
            options={'ordering': ('pre_mes',)},
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['est_id', 'tai_periodo'], name='anuarios_te_est_id__dc1e12_idx'),
        ),
    ]
