# Generated by Django 2.1.1 on 2019-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuarios', '0003_auto_20190208_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiacionmaxima',
            options={'ordering': ('rad_mes',)},
        ),
        migrations.AlterModelOptions(
            name='radiacionminima',
            options={'ordering': ('rad_mes',)},
        ),
        migrations.AlterModelOptions(
            name='viento',
            options={'ordering': ('vie_mes',)},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['est_id', 'cau_periodo'], name='anuarios_ca_est_id__2b4a97_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['est_id', 'hai_periodo'], name='anuarios_hu_est_id__2d9ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['est_id', 'hsu_periodo'], name='anuarios_hu_est_id__3d3ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['est_id', 'nag_periodo'], name='anuarios_ni_est_id__61240e_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['est_id', 'pat_periodo'], name='anuarios_pr_est_id__0a28a0_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionmaxima',
            index=models.Index(fields=['est_id', 'rad_periodo'], name='anuarios_ra_est_id__9377cd_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionminima',
            index=models.Index(fields=['est_id', 'rad_periodo'], name='anuarios_ra_est_id__eb906c_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['est_id', 'tag_periodo'], name='anuarios_te_est_id__9a458c_idx'),
        ),
        migrations.AddIndex(
            model_name='viento',
            index=models.Index(fields=['est_id', 'vie_periodo'], name='anuarios_vi_est_id__622a42_idx'),
        ),
    ]
