# Generated by Django 2.0.3 on 2018-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('mar_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('mar_nombre', models.CharField(max_length=25, verbose_name='Marca')),
            ],
        ),
    ]
