# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('con_fecha_ini', models.DateField(verbose_name='Fecha inicio')),
                ('con_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('con_estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('sen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.Sensor', verbose_name='Sensor')),
            ],
            options={
                'ordering': ['est_id'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('uni_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('uni_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('uni_sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'ordering': ['uni_id'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('var_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('var_codigo', models.CharField(max_length=6, verbose_name='Codigo')),
                ('var_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('var_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Maximo')),
                ('var_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Minimo')),
                ('var_sos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sospechoso')),
                ('var_err', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Error')),
                ('var_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Error minimo')),
                ('var_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('uni_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Unidad', verbose_name='Unidad')),
            ],
            options={
                'ordering': ['var_id'],
            },
        ),
        migrations.AddField(
            model_name='control',
            name='var_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable'),
        ),
    ]
