# Generated by Django 4.2.7 on 2024-02-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variable",
            name="is_cumulative",
        ),
        migrations.AddField(
            model_name="variable",
            name="nature",
            field=models.CharField(
                choices=[("sum", "sum"), ("average", "average"), ("value", "value")],
                default="value",
                max_length=10,
                verbose_name="Nature",
            ),
        ),
    ]
