# Generated by Django 2.1.1 on 2019-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='var_modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
