# Generated by Django 2.1.1 on 2019-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0002_variable_var_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroProcesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=10, verbose_name='Parametro')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estadistico', models.CharField(max_length=10, verbose_name='Código')),
                ('unidad', models.CharField(max_length=10, verbose_name='Unidad de Medidad')),
            ],
        ),
    ]
