# Generated by Django 2.1.1 on 2019-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0003_parametroprocesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroprocesado',
            name='unidad',
            field=models.CharField(max_length=20, verbose_name='Unidad de Medidad'),
        ),
    ]
