# Generated by Django 5.0.3 on 2024-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variable", "0004_alter_sensorinstallation_owner_alter_unit_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorinstallation",
            old_name="permissions_level",
            new_name="visibility",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="permissions_level",
            new_name="visibility",
        ),
        migrations.RenameField(
            model_name="variable",
            old_name="permissions_level",
            new_name="visibility",
        ),
    ]
