# Generated by Django 2.1.1 on 2019-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0004_auto_20190424_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroprocesado',
            name='estadistico',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
