# Generated by Django 2.1.1 on 2019-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0005_auto_20190424_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroprocesado',
            name='unidad',
            field=models.CharField(max_length=50, verbose_name='Unidad de Medidad'),
        ),
    ]
