# Generated by Django 2.1.1 on 2019-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0006_auto_20190424_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=10, verbose_name='Parametro')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estadistico', models.CharField(max_length=20, verbose_name='Código')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad de Medidad')),
                ('trasmision', models.CharField(max_length=10, verbose_name='Transmision')),
            ],
        ),
        migrations.DeleteModel(
            name='ParametroProcesado',
        ),
    ]
