# Generated by Django 2.1.1 on 2019-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0007_auto_20190425_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametro',
            old_name='trasmision',
            new_name='transmision',
        ),
    ]
