# Generated by Django 5.1 on 2024-09-11 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0008_remove_variable_automatic_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='diff_warning',
        ),
        migrations.AlterField(
            model_name='variable',
            name='outlier_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The statistical deviation for defining outliers, in times thestandard deviation (sigma)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sigmas (outliers)'),
        ),
    ]
