# Generated by Django 2.1.1 on 2019-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0008_auto_20190425_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='tipo',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
