# Generated by Django 2.1.1 on 2019-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0009_parametro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='transmision',
        ),
        migrations.AddField(
            model_name='parametro',
            name='frecuencia',
            field=models.CharField(max_length=10, null=True, verbose_name='Frecuencia'),
        ),
    ]
