# Generated by Django 2.2.1 on 2019-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0010_auto_20190425_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='es_acumulada',
            field=models.BooleanField(default=True, verbose_name='Acumulada (check)/ Promediada'),
        ),
        migrations.AddField(
            model_name='variable',
            name='reporte_automatico',
            field=models.BooleanField(default=True, verbose_name='Reporte Automático'),
        ),
        migrations.AddField(
            model_name='variable',
            name='umbral_completo',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Umbral completo (%)'),
        ),
    ]
