# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('cru_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
            options={
                'ordering': ('cru_id', 'est_id', 'var_id'),
            },
        ),
    ]
