# Generated by Django 2.0.3 on 2018-09-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0004_auto_20180814_1053'),
        ('variable', '0001_initial'),
        ('cruce', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cruce',
            unique_together={('est_id', 'var_id')},
        ),
    ]
