# Generated by Django 3.2.14 on 2023-04-15 03:19

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolarWind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                (
                    "speed",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, null=True, verbose_name="Speed"
                    ),
                ),
                (
                    "direction",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Direction",
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AirTemperature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AtmosphericPressure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BatteryVoltage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChlorineConcentrationDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlowManual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, null=True, verbose_name="Value"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Humidity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndirectRadiation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OxygenConcentrationDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PercentageOxygenConcentrationDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PhycocyaninDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Precipitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, null=True, verbose_name="Total"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RedoxPotentialDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SoilMoisture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoilTemperature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SolarRadiation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StripLevelReading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, null=True, verbose_name="Value"
                    ),
                ),
                (
                    "uncertainty",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Uncertainty",
                    ),
                ),
                (
                    "data_import_date",
                    models.DateTimeField(verbose_name="Data import date"),
                ),
                (
                    "data_start_date",
                    models.DateTimeField(verbose_name="Data start date"),
                ),
                ("calibrated", models.BooleanField(verbose_name="Calibrated")),
                (
                    "comments",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Comments"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WaterAcidityDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WaterLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaterTemperature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaterTemperatureDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WaterTurbidityDepth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(verbose_name="Depth")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WindDirection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WindVelocity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("station_id", models.PositiveIntegerField(verbose_name="station_id")),
                (
                    "used_for_daily",
                    models.BooleanField(default=False, verbose_name="used_for_daily"),
                ),
                ("completeness", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Average",
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="Minimum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="waterturbiditydepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_wate_station_29158d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperaturedepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_wate_station_7c3f37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wateraciditydepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_wate_station_b94319_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="striplevelreading",
            index=models.Index(
                fields=["station_id", "data_import_date"],
                name="hourly_stri_station_442487_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="striplevelreading",
            index=models.Index(
                fields=["station_id", "data_start_date", "time"],
                name="hourly_stri_station_31d49c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="striplevelreading",
            index=models.Index(
                fields=["data_import_date"], name="hourly_stri_data_im_f87faf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redoxpotentialdepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_redo_station_fe0e2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phycocyanindepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_phyc_station_120a69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="percentageoxygenconcentrationdepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_perc_station_8b4449_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="oxygenconcentrationdepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_oxyg_station_2d6a10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chlorineconcentrationdepth",
            index=models.Index(
                fields=["station_id", "depth", "time"],
                name="hourly_chlo_station_f2be21_idx",
            ),
        ),
    ]
