# Generated by Django 3.2.14 on 2023-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hourly", "0003_auto_20230621_0111"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_airt_used_fo_23e844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_airt_station_e1045a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_airt_time_b44a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_atmo_used_fo_500960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_atmo_station_c15c6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_atmo_time_d0f9aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_batt_used_fo_5ba9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_batt_station_7669a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_batt_time_847ab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_flow_used_fo_22c225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_flow_station_0adb55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_flow_time_2ac0c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_flow_used_fo_f8c2cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_flow_station_890c0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_flow_time_7d3d38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_humi_used_fo_b25212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_humi_station_ffee5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_humi_time_120062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_indi_used_fo_523723_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_indi_station_ff19e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_indi_time_b6aed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_prec_used_fo_743168_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_prec_station_cc2faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_prec_time_2e622e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_soil_used_fo_727ee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_soil_station_573fbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_soil_time_1e70f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_soil_used_fo_147baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_soil_station_623419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_soil_time_0cc4ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_sola_used_fo_65ebd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_sola_station_8f4283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_sola_time_a31d7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_wate_used_fo_b22608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_wate_station_709b7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_wate_time_44034b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_wate_used_fo_eecb2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_wate_station_e32e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_wate_time_88172b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_wind_used_fo_0feb71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_wind_station_bd67b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_wind_time_969c7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["used_for_daily"], name="hourly_wind_used_fo_a251cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["station_id", "time"], name="hourly_wind_station_6a28f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["time", "station_id"], name="hourly_wind_time_134848_idx"
            ),
        ),
    ]
