# Generated by Django 2.1.1 on 2019-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('dat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('dat_codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('dat_modelo', models.CharField(max_length=25, null=True, verbose_name='Modelo')),
                ('dat_serial', models.CharField(max_length=25, null=True, verbose_name='Serial')),
                ('dat_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('mar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca')),
            ],
            options={
                'ordering': ('dat_codigo',),
            },
        ),
    ]
