site_name: Paricia user manual
repo_url: https://github.com/ImperialCollegeLondon/paricia

docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../site/en'                      # Where to put the English HTML files

theme:
  name: "material"
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  Language: en
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"
  - markdown_include.include:
      base_path: .
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/yesplan.css                  # CSS is shared by all languages

extra:                                              # Language Selection
  alternate:  
      # Switch to English
    - name: English
      link: /en/
      lang: en
    # Switch to Spanish
    - name: Español
      link: /es/
      lang: es


plugins:
  - search:
      lang: en                                      # Set language for search
  - gen-files:
      scripts:
        - ../../includes/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
            members: true
          paths: [measurement]
  - caption:
      figure:
        ignore_classes: ["no-caption"]

nav:
  - Home: index.md
  - User Guide:
      - Introduction: introduction.md
      - Reports: reports.md
      - Permissions: permissions.md
      - Adding elements: adding_elements.md
      - Importing Data: importing_data.md
      - Validation: validation.md
  - Developer Guide:
      - Contributing: contributing.md
      - Installation: installation.md
      - Quality assurance: quality_assurance.md
      - Synthetic data: synthetic_data.md
      - Administrators: admin.md
      - Code structure:
          - Index: Applications/index.md
          - Formatting: Applications/formatting.md
          - Variables: Applications/variable.md
          - Sensors: Applications/sensor.md
          - Stations: Applications/station.md
          - Measurements: Applications/measurement.md
          - Importing: Applications/importing.md
      - API Reference: reference/
