# Generated by Django 2.2.1 on 2019-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstCaudal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='maximo valor en el dia')),
                ('max_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del maximo')),
                ('min_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='minimo valor en el dia')),
                ('min_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del minimo')),
                ('usado_para_anual', models.BooleanField(default=False, verbose_name='Usado para anual')),
                ('per10', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentil 10')),
                ('per50', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentil 50')),
                ('per95', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentil 95')),
                ('dias0', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dias sin lluvia')),
            ],
        ),
        migrations.CreateModel(
            name='EstPrecipitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField(db_index=True, verbose_name='estacion_id')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('usado_para_anual', models.BooleanField(default=False, verbose_name='Usado para anual')),
                ('max_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='maximo valor en el dia')),
                ('max_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del maximo')),
                ('min_dia_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='minimo valor en el dia')),
                ('min_dia_dia', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dia del minimo')),
                ('prom_mes', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Promedio del mes')),
                ('per10', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentil 10')),
                ('per50', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='mediana 50')),
                ('per95', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentil 95')),
                ('dias0', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dias sin lluvia')),
                ('dias01', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='dias lluvias de 0.1')),
            ],
        ),
        migrations.AddIndex(
            model_name='estprecipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='indices_est_fecha_ba1e7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estprecipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='estcaudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='indices_est_fecha_afe26b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estcaudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
