# Generated by Django 2.1.1 on 2019-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variable', '0001_initial'),
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioValidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.SmallIntegerField(db_index=True)),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('validado_id', models.PositiveIntegerField(verbose_name='Validación')),
                ('comentario', models.CharField(max_length=350, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fecha_validacion', models.DateField(verbose_name='Fecha validación')),
                ('fecha_inicio_datos', models.DateTimeField(verbose_name='Fecha inicio datos')),
                ('fecha_fin_datos', models.DateTimeField(verbose_name='Fecha fin datos')),
                ('comentario', models.CharField(max_length=350, verbose_name='Comentario')),
            ],
            options={
                'ordering': ('val_id', 'est_id', 'var_id'),
            },
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('usado_para_horario', models.BooleanField(default=False, verbose_name='Usado en horario')),
                ('validacion', models.PositiveSmallIntegerField(verbose_name='Validación')),
            ],
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_816544_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_7115b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='velocidadviento',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddField(
            model_name='validacion',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='var_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_6fd6da_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_092f5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaaire',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_da2599_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_feae85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaagua',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_a0a778_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_6e6414_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiacionsolar',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_886ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_422e6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presionatmosferica',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_f2f66b_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_40d005_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_80e9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_83156c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivelagua',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_507eea_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_cdcf90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadsuelo',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_17db26_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_18af08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadaire',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_f3214b_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_33951a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direccionviento',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['variable_id', 'estacion_id', 'validado_id'], name='validacion__variabl_c4259a_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['variable_id', 'validado_id', 'estacion_id'], name='validacion__variabl_25db49_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['estacion_id', 'variable_id', 'validado_id'], name='validacion__estacio_fb9f89_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['estacion_id', 'validado_id', 'variable_id'], name='validacion__estacio_2009c1_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['validado_id', 'estacion_id', 'variable_id'], name='validacion__validad_bdffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariovalidacion',
            index=models.Index(fields=['validado_id', 'variable_id', 'estacion_id'], name='validacion__validad_41548e_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='validacion__fecha_5179df_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['usado_para_horario', 'id'], name='validacion__usado_p_5f4dd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha', 'validacion')},
        ),
        migrations.AddIndex(
            model_name='validacion',
            index=models.Index(fields=['var_id', 'est_id'], name='validacion__var_id__a60fe3_idx'),
        ),
    ]
