# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('val_fecha', models.DateField(verbose_name='Fecha')),
                ('val_num_dat', models.IntegerField(default=0, verbose_name='Número de Datos')),
                ('val_fre_reg', models.IntegerField(default=0, verbose_name='Número de Registros')),
                ('val_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Procentaje')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
            options={
                'ordering': ('val_id', 'est_id', 'var_id'),
            },
        ),
    ]
