# Generated by Django 2.2.1 on 2020-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturaaire',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='temperaturaaire',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
    ]
