# Generated by Django 2.2.1 on 2020-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_auto_20200310_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='caudal',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='caudal',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='direccionviento',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='direccionviento',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='humedadaire',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='humedadaire',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='humedadsuelo',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='humedadsuelo',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='nivelagua',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='nivelagua',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='presionatmosferica',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='presionatmosferica',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='radiacionsolar',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='radiacionsolar',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='temperaturaagua',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='temperaturaagua',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
        migrations.AddField(
            model_name='velocidadviento',
            name='maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo'),
        ),
        migrations.AddField(
            model_name='velocidadviento',
            name='minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo'),
        ),
    ]
