# Generated by Django 3.0.11 on 2022-07-20 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formatting", "0001_initial"),
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImportFull",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "filepath",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="File"
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "download_original_file",
                        "Download the original file that was uploaded to the system.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataImportTemp",
            fields=[
                (
                    "data_import_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="End date"
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observations/Notes"
                    ),
                ),
                ("file", models.FileField(upload_to="files/tmp/", verbose_name="File")),
                (
                    "format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="formatting.Format",
                        verbose_name="Format",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.Station",
                        verbose_name="Station",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
