# Generated by Django 5.1 on 2024-08-22 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimportfull',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dataimporttemp',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataimportfull',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataimporttemp',
            name='user',
        ),
        migrations.AddField(
            model_name='dataimportfull',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataimportfull',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=8),
        ),
        migrations.AddField(
            model_name='dataimporttemp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataimporttemp',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=8),
        ),
    ]
