# Generated by Django 5.1 on 2024-08-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0002_association_owner_association_visibility_and_more'),
        ('importing', '0002_initial'),
        ('station', '0011_alter_station_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimporttemp',
            name='format',
        ),
        migrations.RemoveField(
            model_name='dataimporttemp',
            name='station',
        ),
        migrations.RemoveField(
            model_name='dataimporttemp',
            name='user',
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=8)),
                ('data_import_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('rawfile', models.FileField(upload_to='', verbose_name='Data file')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End date')),
                ('records', models.IntegerField(blank=True, verbose_name='Records')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations/Notes')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formatting.format', verbose_name='Format')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.station', verbose_name='Station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DataImportFull',
        ),
        migrations.DeleteModel(
            name='DataImportTemp',
        ),
    ]
