# Generated by Django 5.1 on 2024-09-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0006_alter_classification_accumulate_and_more'),
        ('importing', '0005_alter_dataimport_owner_alter_dataimport_visibility'),
        ('station', '0015_remove_deltat_station_station_delta_t_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='data_import_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of submission of the data.', verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date of the data.', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='format',
            field=models.ForeignKey(help_text='Format of the data.', on_delete=django.db.models.deletion.PROTECT, to='formatting.format', verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='observations',
            field=models.TextField(blank=True, help_text='Notes or observations about the data.', null=True, verbose_name='Observations/Notes'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='rawfile',
            field=models.FileField(help_text='File with the data to be imported.', upload_to='', verbose_name='Data file'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='records',
            field=models.IntegerField(blank=True, help_text='Number of records in the data.', null=True, verbose_name='Records'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date of the data.', null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='station',
            field=models.ForeignKey(help_text='Station to which the data belongs.', on_delete=django.db.models.deletion.PROTECT, to='station.station', verbose_name='Station'),
        ),
    ]
