# Generated by Django 5.2.8 on 2026-02-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0007_alter_dataimport_owner'),
        ('station', '0018_station_variables'),
        ('variable', '0010_alter_sensorinstallation_owner_alter_unit_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingsboardImportMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the mapping.', max_length=255, verbose_name='Name')),
                ('device_id', models.CharField(help_text='Id of the thingsboard device.', max_length=255, verbose_name='Device ID')),
                ('station', models.ForeignKey(help_text='Station to which the data belongs.', on_delete=django.db.models.deletion.PROTECT, to='station.station', verbose_name='Station')),
                ('variable', models.ForeignKey(help_text='Variable name in the data import.', on_delete=django.db.models.deletion.PROTECT, to='variable.variable', verbose_name='Variable')),
            ],
        ),
    ]
