# Generated by Django 5.2.11 on 2026-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0008_thingsboardimportmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Origin of the data imported.', verbose_name='Origin')),
            ],
        ),
    ]
