# Generated by Django 5.2.11 on 2026-02-19 16:34

from django.db import migrations

from ..utils import create_default_origins, remove_default_origins


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0009_importorigin'),
    ]

    operations = [
        migrations.RunPython(create_default_origins, remove_default_origins),
    ]
