# Generated by Django 5.2.8 on 2026-02-23 07:08

import django.db.models.deletion
import importing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0010_initial_data_origins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='origin',
            field=models.ForeignKey(default=importing.models.ImportOrigin.get_default, help_text='Origin of the imported data', on_delete=django.db.models.deletion.PROTECT, to='importing.importorigin'),
        ),
    ]
