# Generated by Django 5.2.8 on 2026-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0011_dataimport_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingsboardimportmap',
            name='device_id',
        ),
        migrations.AddField(
            model_name='thingsboardimportmap',
            name='tb_device_name',
            field=models.CharField(default=' ', help_text='The name of the device in Thingsboard.', max_length=255, verbose_name='Thingsboard Device Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thingsboardimportmap',
            name='tb_variable',
            field=models.CharField(help_text='The name of the variable in Thingsboard.', max_length=255, verbose_name='Thingsboard Variable'),
        ),
    ]
