# Generated by Django 5.2.8 on 2026-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0011_dataimport_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingsboardimportmap',
            name='device_id',
        ),
        migrations.AddField(
            model_name='thingsboardimportmap',
            name='tb_device_name',
            field=models.CharField(blank=True, help_text='The name of the device in Thingsboard (what is shown in the Thingsboard device). Optional, for easier identification, but not required as the device_id is the unique identifier.', max_length=255, null=True, verbose_name='Thingsboard Device Name'),
        ),
    ]
