# Generated by Django 5.2.8 on 2026-04-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0012_remove_thingsboardimportmap_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayerImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8)),
                ('name', models.CharField(help_text='Name of the layer to be imported.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the layer to be imported.', null=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Tiff file with the layer to be imported. Must be a georeferenced raster file.', upload_to='', verbose_name='Layer file')),
                ('owner', models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
