# Generated by Django 5.2.8 on 2026-04-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0012_remove_thingsboardimportmap_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimport',
            name='reprocess',
        ),
    ]
