# Generated by Django 5.2.8 on 2026-04-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_owner(apps, schema_editor):
    ThingsboardImportMap = apps.get_model('importing', 'ThingsboardImportMap')

    for tb_map in ThingsboardImportMap.objects.filter(owner__isnull=True).iterator():
        tb_map.owner = tb_map.station.owner
        tb_map.save()


def reverse_set_default_owner(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0014_maplayerimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thingsboardimportmap',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_owner, reverse_set_default_owner),
        migrations.AlterField(
            model_name='thingsboardimportmap',
            name='owner',
            field=models.ForeignKey(blank=False, help_text='Owner of the mapping.', null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thingsboardimportmap',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
    ]
