# Generated by Django 5.2.8 on 2026-05-21 13:29

import django.core.validators
import django.db.models.deletion
import importing.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0015_thingsboardimportmap_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayerimport',
            name='file',
            field=models.FileField(help_text='Must be a tiff file. File size must not exceed 100 MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'tiff']), importing.utils.validate_layer_file_size], verbose_name='Layer file'),
        ),
        migrations.AlterField(
            model_name='thingsboardimportmap',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
