# Generated by Django 5.2.8 on 2026-05-26 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0007_alter_classification_owner_alter_date_owner_and_more'),
        ('importing', '0015_thingsboardimportmap_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='format',
            field=models.ForeignKey(blank=True, help_text='Format of the data.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.format', verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='thingsboardimportmap',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
