# Generated by Django 5.2.8 on 2026-08-14 09:23

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0016_alter_maplayerimport_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayerimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The time at which the layer was last updated.', verbose_name='Updated at', default=timezone.now),
            preserve_default=False,
        ),
    ]
