# Generated by Django 3.2.14 on 2023-04-15 03:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="station/basin_image/",
                        verbose_name="Photography/Map",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="station/basin_file/",
                        verbose_name="File(PDF)",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Ecosystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="station/place_image/",
                        verbose_name="Photography/Map",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PlaceBasin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="station/place_basin_image/",
                        verbose_name="Photography/Map",
                    ),
                ),
                (
                    "basin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.basin",
                        verbose_name="Basin",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.place",
                        verbose_name="Place",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("place", "basin")},
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="StationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("station_code", models.CharField(max_length=32, verbose_name="Code")),
                (
                    "station_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "station_state",
                    models.BooleanField(default=True, verbose_name="Operational"),
                ),
                (
                    "station_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=14,
                        max_digits=17,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "station_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=14,
                        max_digits=17,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "station_altitude",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(6000),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Altitude",
                    ),
                ),
                (
                    "station_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="station/station_file/",
                        verbose_name="Photography/File",
                    ),
                ),
                (
                    "station_external",
                    models.BooleanField(default=False, verbose_name="External"),
                ),
                (
                    "influence_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Área of input (km)",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "ecosystem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.ecosystem",
                        verbose_name="Ecosystem",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.institution",
                        verbose_name="Institution",
                    ),
                ),
                (
                    "place_basin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.placebasin",
                        verbose_name="Place-Basin",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.region",
                        verbose_name="Region/Province/Department",
                    ),
                ),
                (
                    "station_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="station.stationtype",
                        verbose_name="StationType",
                    ),
                ),
            ],
            options={
                "ordering": ("station_id",),
            },
        ),
        migrations.CreateModel(
            name="DeltaT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("delta_t", models.PositiveSmallIntegerField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="station.station",
                        verbose_name="Station",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
