# Generated by Django 4.2.7 on 2023-11-16 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='timezone',
            field=models.CharField(choices=[('London', 'Europe/London'), ('Paris', 'Europe/Paris'), ('New York', 'America/New_York')], default=datetime.datetime(2023, 11, 16, 11, 45, 57, 843717, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
