# Generated by Django 4.2.7 on 2024-02-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("station", "0003_alter_station_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="permissions_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("internal", "Internal"),
                    ("private", "Private"),
                ],
                default="private",
                max_length=8,
            ),
        ),
    ]
