# Generated by Django 5.0.2 on 2024-02-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_basin_owner_basin_permissions_level_country_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("id",), "verbose_name_plural": "countries"},
        ),
        migrations.AddField(
            model_name="placebasin",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placebasin",
            name="permissions_level",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=8,
            ),
        ),
    ]
