# Generated by Django 5.1.1 on 2024-09-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0015_remove_deltat_station_station_delta_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='delta_t',
        ),
        migrations.DeleteModel(
            name='DeltaT',
        ),
    ]
