# Generated by Django 5.1.1 on 2024-10-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0016_remove_station_delta_t_delete_deltat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region within the Country where the station is located.', null=True, on_delete=django.db.models.deletion.PROTECT, to='station.region', verbose_name='Region'),
        ),
    ]
