# Generated by Django 5.1.2 on 2024-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0017_alter_basin_owner_alter_country_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='variables',
            field=models.CharField(default='', editable=False, help_text='Comma-separated list of variables measured by the station.', max_length=100, verbose_name='Stored variables'),
        ),
    ]
