from django.urls import path

from .views import (
    BasinCreateView,
    BasinDeleteView,
    BasinDetailView,
    BasinEditView,
    BasinListView,
    CountryCreateView,
    CountryDeleteView,
    CountryDetailView,
    CountryEditView,
    CountryListView,
    EcosystemCreateView,
    EcosystemDeleteView,
    EcosystemDetailView,
    EcosystemEditView,
    EcosystemListView,
    InstitutionCreateView,
    InstitutionDeleteView,
    InstitutionDetailView,
    InstitutionEditView,
    InstitutionListView,
    PlaceBasinCreateView,
    PlaceBasinDeleteView,
    PlaceBasinDetailView,
    PlaceBasinEditView,
    PlaceBasinListView,
    PlaceCreateView,
    PlaceDeleteView,
    PlaceDetailView,
    PlaceEditView,
    PlaceListView,
    RegionCreateView,
    RegionDeleteView,
    RegionDetailView,
    RegionEditView,
    RegionListView,
    StationCreateView,
    StationDeleteView,
    StationDetailView,
    StationEditView,
    StationListView,
    StationTypeCreateView,
    StationTypeDeleteView,
    StationTypeDetailView,
    StationTypeEditView,
    StationTypeListView,
)

app_name = "station"
urlpatterns = [
    path("basin/<int:pk>", BasinDetailView.as_view(), name="basin_detail"),
    path("country/<int:pk>", CountryDetailView.as_view(), name="country_detail"),
    path("ecosystem/<int:pk>", EcosystemDetailView.as_view(), name="ecosystem_detail"),
    path(
        "institution/<int:pk>",
        InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path("place/<int:pk>", PlaceDetailView.as_view(), name="place_detail"),
    path(
        "stationtype/<int:pk>",
        StationTypeDetailView.as_view(),
        name="stationtype_detail",
    ),
    path("region/<int:pk>", RegionDetailView.as_view(), name="region_detail"),
    path(
        "placebasin/<int:pk>", PlaceBasinDetailView.as_view(), name="placebasin_detail"
    ),
    path("station/<int:pk>", StationDetailView.as_view(), name="station_detail"),
    path("basin/create/", BasinCreateView.as_view(), name="basin_create"),
    path("country/create/", CountryCreateView.as_view(), name="country_create"),
    path("ecosystem/create/", EcosystemCreateView.as_view(), name="ecosystem_create"),
    path(
        "institution/create/",
        InstitutionCreateView.as_view(),
        name="institution_create",
    ),
    path("place/create/", PlaceCreateView.as_view(), name="place_create"),
    path(
        "stationtype/create/",
        StationTypeCreateView.as_view(),
        name="stationtype_create",
    ),
    path("region/create/", RegionCreateView.as_view(), name="region_create"),
    path(
        "placebasin/create/", PlaceBasinCreateView.as_view(), name="placebasin_create"
    ),
    path("station/create/", StationCreateView.as_view(), name="station_create"),
    path("basin/edit/<int:pk>", BasinEditView.as_view(), name="basin_edit"),
    path("country/edit/<int:pk>", CountryEditView.as_view(), name="country_edit"),
    path("ecosystem/edit/<int:pk>", EcosystemEditView.as_view(), name="ecosystem_edit"),
    path(
        "institution/edit/<int:pk>",
        InstitutionEditView.as_view(),
        name="institution_edit",
    ),
    path("place/edit/<int:pk>", PlaceEditView.as_view(), name="place_edit"),
    path(
        "stationtype/edit/<int:pk>",
        StationTypeEditView.as_view(),
        name="stationtype_edit",
    ),
    path("region/edit/<int:pk>", RegionEditView.as_view(), name="region_edit"),
    path(
        "placebasin/edit/<int:pk>", PlaceBasinEditView.as_view(), name="placebasin_edit"
    ),
    path("station/edit/<int:pk>", StationEditView.as_view(), name="station_edit"),
    path("basin/delete/<int:pk>", BasinDeleteView.as_view(), name="basin_delete"),
    path("country/delete/<int:pk>", CountryDeleteView.as_view(), name="country_delete"),
    path(
        "ecosystem/delete/<int:pk>",
        EcosystemDeleteView.as_view(),
        name="ecosystem_delete",
    ),
    path(
        "institution/delete/<int:pk>",
        InstitutionDeleteView.as_view(),
        name="institution_delete",
    ),
    path("place/delete/<int:pk>", PlaceDeleteView.as_view(), name="place_delete"),
    path(
        "stationtype/delete/<int:pk>",
        StationTypeDeleteView.as_view(),
        name="stationtype_delete",
    ),
    path("region/delete/<int:pk>", RegionDeleteView.as_view(), name="region_delete"),
    path(
        "placebasin/delete/<int:pk>",
        PlaceBasinDeleteView.as_view(),
        name="placebasin_delete",
    ),
    path("station/delete/<int:pk>", StationDeleteView.as_view(), name="station_delete"),
    path("basin/", BasinListView.as_view(), name="basin_list"),
    path("country/", CountryListView.as_view(), name="country_list"),
    path("ecosystem/", EcosystemListView.as_view(), name="ecosystem_list"),
    path("institution/", InstitutionListView.as_view(), name="institution_list"),
    path("place/", PlaceListView.as_view(), name="place_list"),
    path("stationtype/", StationTypeListView.as_view(), name="stationtype_list"),
    path("region/", RegionListView.as_view(), name="region_list"),
    path("placebasin/", PlaceBasinListView.as_view(), name="placebasin_list"),
    path("station/", StationListView.as_view(), name="station_list"),
]
