# Generated by Django 2.2.1 on 2019-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caudal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='HumedadSuelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='PresionAtmosferica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionSolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAgua',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=7, max_digits=15, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_vel_usado_p_00a8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='velocidadviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_vel_fecha_f59152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='velocidadviento',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_tem_usado_p_5b8910_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_tem_fecha_6eb26a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_tem_usado_p_98e561_idx'),
        ),
        migrations.AddIndex(
            model_name='temperaturaagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_tem_fecha_a0f8d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temperaturaagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_rad_usado_p_3ba7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='radiacionsolar',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_rad_fecha_d64225_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='radiacionsolar',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_pre_usado_p_1e7f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='presionatmosferica',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_pre_fecha_0a1653_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presionatmosferica',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_pre_usado_p_8db3de_idx'),
        ),
        migrations.AddIndex(
            model_name='precipitacion',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_pre_fecha_ff1637_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitacion',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_niv_usado_p_3cd2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelagua',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_niv_fecha_8bb3ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivelagua',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_hum_usado_p_7143f5_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadsuelo',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_hum_fecha_7e5151_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadsuelo',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_hum_usado_p_cc5953_idx'),
        ),
        migrations.AddIndex(
            model_name='humedadaire',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_hum_fecha_bd6901_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humedadaire',
            unique_together={('estacion_id', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_cau_usado_p_16b14f_idx'),
        ),
        migrations.AddIndex(
            model_name='caudal',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_cau_fecha_981587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caudal',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
