# Generated by Django 2.2.1 on 2019-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('estacion_id', models.PositiveIntegerField(verbose_name='estacion_id')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('max_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('min_abs', models.DecimalField(decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('completo_mediciones', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Completo mediciones %')),
                ('usado_para_diario', models.BooleanField(default=False, verbose_name='Usado para diario')),
            ],
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['usado_para_diario', 'id'], name='horario_dir_usado_p_4100cc_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionviento',
            index=models.Index(fields=['fecha', 'estacion_id'], name='horario_dir_fecha_35e685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='direccionviento',
            unique_together={('estacion_id', 'fecha')},
        ),
    ]
