# Generated by Django 3.2.14 on 2023-06-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0002_auto_20230621_0111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airtemperature",
            name="value",
        ),
        migrations.RemoveField(
            model_name="atmosphericpressure",
            name="value",
        ),
        migrations.RemoveField(
            model_name="batteryvoltage",
            name="value",
        ),
        migrations.RemoveField(
            model_name="chlorineconcentrationdepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="value",
        ),
        migrations.RemoveField(
            model_name="flowmanual",
            name="value",
        ),
        migrations.RemoveField(
            model_name="humidity",
            name="value",
        ),
        migrations.RemoveField(
            model_name="indirectradiation",
            name="value",
        ),
        migrations.RemoveField(
            model_name="oxygenconcentrationdepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="percentageoxygenconcentrationdepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="phycocyanindepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="redoxpotentialdepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="soilmoisture",
            name="value",
        ),
        migrations.RemoveField(
            model_name="soiltemperature",
            name="value",
        ),
        migrations.RemoveField(
            model_name="solarradiation",
            name="value",
        ),
        migrations.RemoveField(
            model_name="wateraciditydepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="waterlevel",
            name="value",
        ),
        migrations.RemoveField(
            model_name="watertemperature",
            name="value",
        ),
        migrations.RemoveField(
            model_name="watertemperaturedepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="waterturbiditydepth",
            name="value",
        ),
        migrations.RemoveField(
            model_name="winddirection",
            name="value",
        ),
        migrations.RemoveField(
            model_name="windvelocity",
            name="value",
        ),
        migrations.AddField(
            model_name="airtemperature",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="atmosphericpressure",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="batteryvoltage",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="chlorineconcentrationdepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="flowmanual",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="humidity",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="indirectradiation",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="oxygenconcentrationdepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="percentageoxygenconcentrationdepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="phycocyanindepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="redoxpotentialdepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="soilmoisture",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="soiltemperature",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="solarradiation",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="wateraciditydepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="waterlevel",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="watertemperature",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="watertemperaturedepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="waterturbiditydepth",
            name="average",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="winddirection",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
        migrations.AddField(
            model_name="windvelocity",
            name="average",
            field=models.DecimalField(
                decimal_places=6, max_digits=14, null=True, verbose_name="Average"
            ),
        ),
    ]
