# Generated by Django 3.2.14 on 2023-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0003_auto_20230621_0216"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_9c113f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airtemperature",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_e188db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_4feb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atmosphericpressure",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_1799b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_dc5c8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryvoltage",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_179edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_051d7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_3656cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_d465a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowmanual",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_27a8df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_d7c6b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humidity",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_083694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_de49cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indirectradiation",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_35bf42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_ce8b84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitation",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_79410d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_330d85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soilmoisture",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_e584de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_47eaf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soiltemperature",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_3365c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_cb76f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarradiation",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_ceae91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_538796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterlevel",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_9e1222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_ecd54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watertemperature",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_8e6ce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_26a5ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winddirection",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_01f4ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["station_id", "time"], name="measurement_station_3f7376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windvelocity",
            index=models.Index(
                fields=["time", "station_id"], name="measurement_time_e1435a_idx"
            ),
        ),
    ]
