# Generated by Django 4.2.7 on 2024-01-17 14:05

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variable", "0001_initial"),
        ("station", "0003_alter_station_timezone"),
        ("measurement", "0004_auto_20230623_0007"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="value"
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="minimum",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("monthly", "Montly"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "used_for_daily",
                    models.BooleanField(
                        default=False,
                        verbose_name="Has data been used already for a daily report?",
                    ),
                ),
                (
                    "used_for_monthly",
                    models.BooleanField(
                        default=False,
                        verbose_name="Has data been used already for a montly report?",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="station.station",
                        verbose_name="Station",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="variable.variable",
                        verbose_name="Variable",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["report_type", "station", "time", "variable"],
                        name="measurement_report__51fccc_idx",
                    )
                ],
            },
        ),
    ]
