# Generated by Django 4.2.7 on 2024-01-17 15:08

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_alter_station_timezone"),
        ("variable", "0001_initial"),
        ("measurement", "0005_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=14, verbose_name="value"
                    ),
                ),
                (
                    "maximum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="maximum",
                    ),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="minimum",
                    ),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(null=True, verbose_name="depth"),
                ),
                (
                    "direction",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="direction",
                    ),
                ),
                (
                    "raw_value",
                    models.DecimalField(
                        decimal_places=6,
                        editable=False,
                        max_digits=14,
                        null=True,
                        verbose_name="raw value",
                    ),
                ),
                (
                    "raw_maximum",
                    models.DecimalField(
                        decimal_places=6,
                        editable=False,
                        max_digits=14,
                        null=True,
                        verbose_name="raw maximum",
                    ),
                ),
                (
                    "raw_minimum",
                    models.DecimalField(
                        decimal_places=6,
                        editable=False,
                        max_digits=14,
                        null=True,
                        verbose_name="raw minimum",
                    ),
                ),
                (
                    "raw_direction",
                    models.DecimalField(
                        decimal_places=6,
                        editable=False,
                        max_digits=14,
                        null=True,
                        verbose_name="raw direction",
                    ),
                ),
                (
                    "raw_depth",
                    models.PositiveSmallIntegerField(
                        editable=False, null=True, verbose_name="raw depth"
                    ),
                ),
                (
                    "used_for_hourly",
                    models.BooleanField(
                        default=False,
                        verbose_name="Has data been used already for an hourly report?",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, verbose_name="Has data been validated?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is data active?"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="station.station",
                        verbose_name="Station",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="variable.variable",
                        verbose_name="Variable",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["station", "time", "variable"],
                        name="measurement_station_322060_idx",
                    )
                ],
            },
        ),
    ]
