# Generated by Django 4.2.7 on 2024-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0006_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="depth",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="depth"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="direction",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=14,
                null=True,
                verbose_name="direction",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active?"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="is_validated",
            field=models.BooleanField(default=False, verbose_name="Validated?"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="maximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=14,
                null=True,
                verbose_name="maximum",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="minimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=14,
                null=True,
                verbose_name="minimum",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_depth",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="raw depth"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_direction",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="raw direction",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_maximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="raw maximum",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_minimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="raw minimum",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                max_digits=14,
                null=True,
                verbose_name="raw value",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="used_for_hourly",
            field=models.BooleanField(default=False, verbose_name="Used for hourly?"),
        ),
        migrations.AlterField(
            model_name="report",
            name="maximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=14,
                null=True,
                verbose_name="maximum",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="minimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=14,
                null=True,
                verbose_name="minimum",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="used_for_daily",
            field=models.BooleanField(default=False, verbose_name="Used for daily?"),
        ),
        migrations.AlterField(
            model_name="report",
            name="used_for_monthly",
            field=models.BooleanField(default=False, verbose_name="Used for monthly?"),
        ),
    ]
