# Generated by Django 4.2.7 on 2024-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "measurement",
            "0007_alter_measurement_depth_alter_measurement_direction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="completeness",
            field=models.DecimalField(decimal_places=1, default=100, max_digits=4),
            preserve_default=False,
        ),
    ]
