# Generated by Django 4.2.7 on 2024-02-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_station_owner_station_permissions_level"),
        ("measurement", "0008_report_completeness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
    ]
