# Generated by Django 4.2.7 on 2024-02-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_station_owner_station_permissions_level"),
        ("measurement", "0009_remove_measurement_used_for_hourly_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
    ]
