# Generated by Django 4.2.7 on 2024-02-27 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0009_alter_measurement_station_alter_report_station"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={},
        ),
    ]
