# Generated by Django 5.0.2 on 2024-03-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "measurement",
            "0010_delete_airtemperature_delete_atmosphericpressure_and_more",
        ),
        ("station", "0007_alter_station_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={},
        ),
        migrations.AlterField(
            model_name="measurement",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.station",
                verbose_name="Station",
            ),
        ),
    ]
