# Generated by Django 5.1.1 on 2024-10-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_alter_measurement_depth_alter_measurement_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='completeness',
            field=models.DecimalField(decimal_places=1, default=100, help_text='Completeness of the report. Eg. a daily report made out of 24 hourly measurements would have a completeness of 100%.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
