# Generated by Django 5.1.1 on 2024-10-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0006_alter_dataimport_data_import_id_and_more'),
        ('measurement', '0014_alter_report_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='data_import',
            field=models.ForeignKey(blank=True, help_text='Data import this measurement belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='importing.dataimport'),
        ),
        migrations.AddField(
            model_name='report',
            name='data_import',
            field=models.ForeignKey(blank=True, help_text='Data import this measurement belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='importing.dataimport'),
        ),
    ]
