# Generated by Django 5.1 on 2024-09-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formatting", "0002_association_owner_association_visibility_and_more"),
        ("station", "0012_alter_placebasin_basin_alter_placebasin_place_and_more"),
        ("variable", "0006_alter_sensorinstallation_sensor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.format",
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="station.station",
                verbose_name="Station",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.format",
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="variable.variable",
                verbose_name="Variable",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.date",
                verbose_name="Date format",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="delimiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.delimiter",
                verbose_name="Delimiter",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="extension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.extension",
                verbose_name="File extension",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formatting.time",
                verbose_name="Time format",
            ),
        ),
    ]
