# Generated by Django 5.1 on 2024-09-05 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0003_alter_association_format_alter_association_station_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='file',
        ),
        migrations.RemoveField(
            model_name='format',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='format',
            name='location',
        ),
        migrations.RemoveField(
            model_name='format',
            name='status',
        ),
        migrations.RemoveField(
            model_name='format',
            name='utc_date',
        ),
        migrations.AlterField(
            model_name='classification',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classification',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.AlterField(
            model_name='date',
            name='code',
            field=models.CharField(help_text='The code used to parse the date column, eg. `%d-%m-%Y`.', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_format',
            field=models.CharField(help_text='The format string for the date column in human readable form, eg.`DD-MM-YYYY`.', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='date',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='date',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='character',
            field=models.CharField(blank=True, help_text='The character used as a delimiter. eg. `,`, `;`, `\\t`.', max_length=10, verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='delimiter_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='name',
            field=models.CharField(help_text='The name of the delimiter. eg. `comma`, `semicolon`, `tab`.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extension',
            name='value',
            field=models.CharField(help_text='The extension value. eg. `xlsx`, `xlx`, `txt`.', max_length=5, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.AlterField(
            model_name='format',
            name='date',
            field=models.ForeignKey(blank=True, help_text='Format for the date column. Only required for text files.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.date', verbose_name='Date format'),
        ),
        migrations.AlterField(
            model_name='format',
            name='date_column',
            field=models.SmallIntegerField(help_text='Index of the date column, starting in 1.', verbose_name='Date column'),
        ),
        migrations.AlterField(
            model_name='format',
            name='delimiter',
            field=models.ForeignKey(blank=True, help_text='The delimiter between columns in the data file. Only required for text files.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.delimiter', verbose_name='Delimiter'),
        ),
        migrations.AlterField(
            model_name='format',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the format.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='format',
            name='extension',
            field=models.ForeignKey(help_text='The extension of the data file.', on_delete=django.db.models.deletion.PROTECT, to='formatting.extension', verbose_name='File extension'),
        ),
        migrations.AlterField(
            model_name='format',
            name='first_row',
            field=models.SmallIntegerField(help_text='First row of the data, excluding any heading.', verbose_name='First row'),
        ),
        migrations.AlterField(
            model_name='format',
            name='footer_rows',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Number of footer rows, to be ignored at the end.', verbose_name='Number of footer rows'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='format_id'),
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(help_text='Short name of the format entry.', max_length=35, verbose_name='Format name'),
        ),
        migrations.AlterField(
            model_name='format',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='format',
            name='time',
            field=models.ForeignKey(blank=True, help_text='Format for the time column. Only required for text files.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.time', verbose_name='Time format'),
        ),
        migrations.AlterField(
            model_name='format',
            name='time_column',
            field=models.SmallIntegerField(help_text='Index of the time column, starting in 1.', verbose_name='Time column'),
        ),
        migrations.AlterField(
            model_name='format',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.AlterField(
            model_name='time',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_format',
            field=models.CharField(help_text='The format string for the date column in human readable form, eg. `HH:MM:SS 24H`', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_id',
            field=models.AutoField(help_text='Primary key.', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='time',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text="Visibility level of the object. WARNING: Changing this setting will affect the permissions of the object. If 'Public', all users will be able to view and associate the object with their own.", max_length=8),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
