# Generated by Django 5.1 on 2024-09-06 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formatting", "0005_alter_classification_accumulate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="accumulate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="When set to a number of minutes, the data will be accumulated over that period.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Accumulate minutes",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="maximum",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Index of the maximum value column, starting in 0.",
                null=True,
                verbose_name="Maximum value column",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="maximum_validator_column",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Index of the maximum value validator column, starting in 0.",
                null=True,
                verbose_name="Maximum value validator column",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="minimum",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Index of the minimum value column, starting in 0.",
                null=True,
                verbose_name="Minimum value column",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="minimum_validator_column",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Index of the minimum value validator column, starting in 0.",
                null=True,
                verbose_name="Minimum value validator column",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="resolution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Resolution of the data. Only used if it is to be accumulated.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Resolution",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="value",
            field=models.PositiveSmallIntegerField(
                help_text="Index of the value column, starting in 0.",
                verbose_name="Value column",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="value_validator_column",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Index of the value validator column, starting in 0.",
                null=True,
                verbose_name="Value validator column",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="date_column",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Index of the date column, starting in 0.",
                verbose_name="Date column",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="first_row",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Index of the first row with data, starting in 0.",
                verbose_name="First row",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="footer_rows",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of footer rows to be ignored at the end.",
                verbose_name="Number of footer rows",
            ),
        ),
        migrations.AlterField(
            model_name="format",
            name="time_column",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Index of the time column, starting in 0.",
                verbose_name="Time column",
            ),
        ),
    ]
