# Generated by Django 5.1.1 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0006_alter_classification_accumulate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='code',
            field=models.CharField(help_text='The code used to parse the date column, eg. `%H:%M:%S`', max_length=20, verbose_name='Code'),
        ),
    ]
