# Generated by Django 5.1.1 on 2024-10-10 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0006_alter_classification_accumulate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='date',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delimiter',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extension',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='format',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='code',
            field=models.CharField(help_text='The code used to parse the date column, eg. `%H:%M:%S`', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='time',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
