# Generated by Django 5.2.8 on 2026-05-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0007_alter_classification_owner_alter_date_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='thingsboard',
            field=models.BooleanField(default=False, help_text='Whether the data is being imported from Thingsboard.', verbose_name='Thingsboard data'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Index of the value column, starting in 0.', null=True, verbose_name='Value column'),
        ),
        migrations.AlterField(
            model_name='format',
            name='date_column',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Index of the date column, starting in 0.', null=True, verbose_name='Date column'),
        ),
        migrations.AlterField(
            model_name='format',
            name='extension',
            field=models.ForeignKey(blank=True, help_text='The extension of the data file.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.extension', verbose_name='File extension'),
        ),
        migrations.AlterField(
            model_name='format',
            name='first_row',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Index of the first row with data, starting in 0.', null=True, verbose_name='First row'),
        ),
        migrations.AlterField(
            model_name='format',
            name='footer_rows',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of footer rows to be ignored at the end.', null=True, verbose_name='Number of footer rows'),
        ),
        migrations.AlterField(
            model_name='format',
            name='time_column',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Index of the time column, starting in 0.', null=True, verbose_name='Time column'),
        ),
    ]
