# Generated by Django 5.2.8 on 2026-05-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0007_alter_classification_owner_alter_date_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='format',
            field=models.ForeignKey(blank=True, help_text='The format of the data file.', null=True, on_delete=django.db.models.deletion.PROTECT, to='formatting.format', verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Index of the value column, starting in 0.', null=True, verbose_name='Value column'),
        ),
    ]
