# Generated by Django 5.2.8 on 2026-09-30 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatting', '0008_format_thingsboard_alter_classification_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='accumulate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If set, measurements will be summed into fixed time windows of this length (in minutes). Leave blank to use unaggregated data.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Accumulate minutes'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='resolution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution of the data.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Resolution'),
        ),
    ]
