# Generated by Django 2.0.3 on 2018-04-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacion', '0001_initial'),
        ('marca', '0001_initial'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMedicion',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('medicion', models.IntegerField(verbose_name='medicion')),
                ('med_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('med_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('med_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Máximo')),
                ('med_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Mínimo')),
                ('log_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('log_accion', models.CharField(max_length=200, verbose_name='Acción')),
                ('log_mensaje', models.TextField(verbose_name='Mensaje')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estación')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
            options={
                'ordering': ('log_fecha',),
            },
        ),
    ]
